### PR TITLE
Upgrade IRATI kernel to 4.1.24

### PR DESCRIPTION
**Pull request by vmaffione**
This is also needed in order to compile IRATI with gcc 6 versions.
I would need ack from everybody is actively testing the stack.

### CODE REVIEW

**Comment by sandervrijders** [comment]
Can we merge this?

**Comment by vmaffione** [comment]
The demonstrator is using this branch, so there is some evidence that there is no regression. Let's wait for @kewinrausch , @edugrasa and other testers

**Comment by sandervrijders** [comment]
Just tried it. Got a compilation error in kernel/trace/trace.c:5440 (defined but not used)

**Comment by sandervrijders** [comment]
Just compiled it on a fresh install, seems to work on my end

**Comment by vmaffione** [comment]
ok thanks for the test

2016-06-01 16:48 GMT+02:00 Sander Vrijders <notifications@github.com>:

> Just compiled it on a fresh install, seems to work on my end
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IRATI/stack/pull/929#issuecomment-223016547>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEsSwfO_5dgm7foCzIy2HiGA7jvHSsZfks5qHZvMgaJpZM4IfryS>
> .
>



-- 
Vincenzo Maffione

**Comment by lbergesio** [comment]
I did a satisfactory small test. Compilation, and app over normal over
shim-eth with 2 nodes worked fine.

2016-06-01 16:49 GMT+02:00 Vincenzo Maffione <notifications@github.com>:

> ok thanks for the test
>
> 2016-06-01 16:48 GMT+02:00 Sander Vrijders <notifications@github.com>:
>
> > Just compiled it on a fresh install, seems to work on my end
> >
> > —
> > You are receiving this because you authored the thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/IRATI/stack/pull/929#issuecomment-223016547>, or
> mute
> > the thread
> > <
> https://github.com/notifications/unsubscribe/AEsSwfO_5dgm7foCzIy2HiGA7jvHSsZfks5qHZvMgaJpZM4IfryS
> >
> > .
> >
>
>
>
> --
> Vincenzo Maffione
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/IRATI/stack/pull/929#issuecomment-223016662>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABtu_LdZIKmxWpuJibaH7n0wIRSlygUAks5qHZvigaJpZM4IfryS>
> .
>



-- 
Leonardo Bergesio
Distributed Applications and Networks Area - DANA
i2CAT Foundation - www.i2cat.net
C/ Gran Capità 2-4, office 109, Nexus I building
08034 Barcelona, Catalonia (Spain)
T: +34 93 567 9926
F: +34 93 553 2520
W: http://dana.i2cat.net

**Comment by vmaffione** [comment]
Yes, the point is that this pull request is not correlated to RINA code. We have chosen the 4.1.x stable version exactly because then we are able to get long-term support, which means merging upstream changes.

**Comment by dstaesse** [comment]
ACK works

**Comment by vmaffione** [comment]
Merging, since it is needed to compile on testbeds of different people

**Pull request merged**
