### PR TITLE
Add support for rate based flow control

### PR DESCRIPTION
**Pull request by miqueltarzan**
Rate based flow control required a few changes in some instrumental functions in DTP, plus a few changes in the DTP and DTCP policy sets in order to: a) comply with the latest version of the specs -split of flow control overrun policy into two versions, for sender and receiver; and b) move reconcile flow control from the DTCP policy set to a more suitable place, in the DTP policy set. 

Maintainers: @msune for rinad/src/ipcm/configuration.cc and @lbergesio for everything else.

### CODE REVIEW

**Comment by sandervrijders** [comment]
@miqueltarzan Could you also please follow the agreed format for commit messages?

As @msune said:

> Please have a look on the mail circulated for having better (more understandable and traceable) 
> commit messages:
> http://chris.beams.io/posts/git-commit/
> 
> The first line of a commit message is the subject, and should be <= 50 characters, and then have 
> a body with the real explanation. Vi and other editors, when set to be the main git editor, they 
> show when you go out of bounds for subject and body of the commit message.

**Comment by dstaesse** [comment]
is someone testing this currently?

**Comment by dstaesse** [comment]
Hi guys, I had a look at the code in this PR. There are a lot of placeholder functions, so this PR looks very incomplete. I would prefer not merging incomplete PR's...

**Comment by vmaffione** [comment]
This PR seems to be inactive. If there is nobody working on it, currently, we could just close it and reopen when necessary. @miqueltarzan ?

**Comment by miqueltarzan** [comment]
@dstaesse and @vmaffione This PR has being used by @kewinrausch to develop the rate-based flow control functionality. The placeholders (not a lot, just a few) were required to not hinder the work by @kewinrausch. Eventually @kewinrausch will ask a PR including this code.

**Comment by kewinrausch** [comment]
I confirm what Miquel said.

**Comment by dstaesse** [comment]
OK, then @vmaffione can close this PR and Kewin should issue a new one.

**Pull request closed without merging**
