### PR TITLE
Debian packaging

### PR DESCRIPTION
**Pull request by jmuchemb**
Not done:
- Java bindings.
- ABI for libraries.

See the added `Debian-packaging.md` file.

Example list of built packages:
```
-rw-r--r-- 1 jm jm      1459 Nov 14 02:29 librina/librina_1.2.0-1777.g2e1cdbc_amd64.changes
-rw-r--r-- 1 jm jm    469104 Nov 14 02:29 librina/librina_1.2.0-1777.g2e1cdbc_amd64.deb
-rw-r--r-- 1 jm jm    551940 Nov 14 02:29 librina/librina-dev_1.2.0-1777.g2e1cdbc_amd64.deb
-rw-r--r-- 1 jm jm    310676 Nov 14 02:29 librina/librina-doc_1.2.0-1777.g2e1cdbc_all.deb
-rw-r--r-- 1 jm jm      2703 Nov 14 02:23 linux/linux_4.1.33+rina65.g2e1cdbc-1_amd64.changes
-rw-r--r-- 1 jm jm    474688 Nov 14 01:56 linux/linux-headers-4.1.0-rina.1-amd64_4.1.33+rina65.g2e1cdbc-1_amd64.deb
-rw-r--r-- 1 jm jm   4767400 Nov 14 02:23 linux/linux-headers-4.1.0-rina.1-common_4.1.33+rina65.g2e1cdbc-1_amd64.deb
-rw-r--r-- 1 jm jm  35223494 Nov 14 02:00 linux/linux-image-4.1.0-rina.1-amd64_4.1.33+rina65.g2e1cdbc-1_amd64.deb
-rw-r--r-- 1 jm jm 368409940 Nov 14 02:23 linux/linux-image-4.1.0-rina.1-amd64-dbg_4.1.33+rina65.g2e1cdbc-1_amd64.deb
-rw-r--r-- 1 jm jm   1044284 Nov 14 02:23 linux/linux-libc-dev_4.1.33+rina65.g2e1cdbc-1_amd64.deb
-rw-r--r-- 1 jm jm    311478 Nov 14 02:23 linux/xen-linux-system-4.1.0-rina.1-amd64_4.1.33+rina65.g2e1cdbc-1_amd64.deb
-rw-r--r-- 1 jm jm    291302 Nov 14 02:34 rinad/librinad_1.2.0-1777.g2e1cdbc_amd64.deb
-rw-r--r-- 1 jm jm   1974886 Nov 14 02:35 rinad/librinad-dev_1.2.0-1777.g2e1cdbc_amd64.deb
-rw-r--r-- 1 jm jm      1441 Nov 14 02:35 rinad/rinad_1.2.0-1777.g2e1cdbc_amd64.changes
-rw-r--r-- 1 jm jm    374620 Nov 14 02:34 rinad/rinad_1.2.0-1777.g2e1cdbc_amd64.deb
-rw-r--r-- 1 jm jm       740 Nov 14 02:36 rina-tools/rina-tools_1.2.0-1777.g2e1cdbc_amd64.changes
-rw-r--r-- 1 jm jm    110532 Nov 14 02:36 rina-tools/rina-tools_1.2.0-1777.g2e1cdbc_amd64.deb
```

### CODE REVIEW

**Comment by jmuchemb** [comment]
Thanks to #1002, I rebased with tests enabled:
```
============================================================================
Testsuite summary for RINA Libraries 1.2.0.1706-6cb8f-dirty
============================================================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 1
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```
\+ another change to use `git describe --dirty` instead of `git describe --dirty` to generate the package versions of userland components.

**Comment by jmuchemb** [comment]
Amended with the last 2 commits with the following changes:
- *.manifest files were missing from librinad
- *.so plugin files moved from librinad-dev to librinad

**Comment by jmuchemb** [comment]
I am currently working on fixing conflicts between Debian patches and  #1010

**Comment by jmuchemb** [comment]
> I am currently working on fixing conflicts between Debian patches and #1010

Done. With another commit to disable debug logs in the kernel (when it is built as a Debian package) since they can cause to much overhead.

**Comment by edugrasa** [comment]
@vmaffione I've no experience with debian packaging, could you review the PR to see if we can merge it?

**Comment by vmaffione** [comment]
I've no experience in Debian, actually.
My opinion is that this is too much stuff. 1694 new files just to build a debian package? It seems wrong? What are those files for? If there is really need for those it makes sense to have another repository just for this.

**Comment by jmuchemb** [comment]
> 1694 new files just to build a debian package?

4 packages:
- librina: 9
- linux: 1670
- rinad: 9
- rina-tools: 6

So I guess your concern is about the kernel package. This looks frightening indeed, but this is a complex task and there's no other way to make a useful package. In particular, someone who installs such package expects to have the same kernel as the official Debian one.

Maybe this wasn't clear but this is actually a fork of the official Debian kernel packaging (actually that of jessie-backports). I did it in a maintainable way. As I documented it, the import of the original Debian packaging is done in a disjoint branch, so that one could easily import/merge new upstream versions (when we do a major upgrade of the kernel).

Also, I already took care of dropping ABI dumps because they're quite big. I didn't pay much attention about the number of files. For each folder in linux/debian:
- bin: 11
- config: 90
- installer: 1160
- lib: 9
- patches: 335
- source: 2
- templates: 51

Because each architecture (and Debian maintains many) requires specific kernel options or build settings, the stats for the config folder is not surprising. bin & lib goes together, providing several maintainer scripts and some of them produce files from templates. templates also contain translations.

Maybe we can remove the whole installer folder. I'm going to check.

**Comment by vmaffione** [comment]
I see. Ok, if you can manage to reduce the size it it would be very nice.
The ideal thing would be to have this debian support in a separate repository (since is so huge), but if it's a lot of work we can also merge it as is.

Btw, it's so many files, where are the instructions to build the packages?

**Comment by jmuchemb** [comment]
> Maybe we can remove the whole installer folder. I'm going to check.

Checked and the installer folder is indeed useless. All files can be removed, with the exception of `linux/debian/installer/package-list`, but the latter can be emptied.

So the PR can be 535 new files. The drawback of removing installer files is that it's one more step to take into account when merging changes from Debian. The packaging of the kernel looks big because I wanted to do minimal changes.

**Comment by vmaffione** [comment]
Why a step more? To empty again the installer folder?

**Comment by jmuchemb** [comment]
> Btw, it's so many files, where are the instructions to build the packages?

For the kernel, it's indeed not trivial, I wrote the `linux/debian/README.RINA` file, as said in the PR description.

For the other packages, it's almost like any other package. I find a waste of time to maintain debian/changelog files, in particular when one wants to build snapshot packages. So before the usual

    # from the librina folder, or rinad, or rina-tools
    dpkg-buildpackage -b

one has to do:

    debian/rules

See also the command in the `debian/rules` files. I wish Debian offered a way to customize what happens before `dpkg-buildpackage` tries to open the `debian/changelog` file.

**Comment by vmaffione** [comment]
Ok, so just running the "debian/rules" script in each of lirbrina/rinad/rina-tools, and the .deb will pop up in the current directory, right?

**Comment by jmuchemb** [comment]
> Why a step more? To empty again the installer folder?

Yes. Currently, the README.RINA file says:
```
1) checkout the commit of the last imported tarball, whose tree only contains
   a ``linux/debian`` folder (next steps are done from ``linux/``)
2) extract the new tarball and remove ``debian/abi`` if necessary
3) run ``debian/rules maintainerclean``
```
Between 2) and 3), I'd have to add:
*) remove everything in ``debian/installer`` except ``debian/installer/package-list`` which must be emptied

**Comment by vmaffione** [comment]
If you wish removing those files it's not worth it (because it makes maintenance more complex), we can keep them.

**Comment by jmuchemb** [comment]
> Ok, so just running the "debian/rules" script in each of lirbrina/rinad/rina-tools, and the .deb will pop up in the current directory, right?

Parent directory. Example
```
$ cd librina
$ debian/rules
$ dpkg-buildpackage -b -uc # -uc to skip gpg signing
$ ls -l ../*.deb
```
Note also that packages depend on each other:
- in order to build librina, you have to install the linux-libc-dev package produced when building the kernel
- for rinad, the development packages of librina must be installed
- and for rina-tools, rinad development packages must be installed (dependencies are such that it also pulls librina development packages)

> The ideal thing would be to have this debian support in a separate repository (since is so huge), but if it's a lot of work we can also merge it as is.

I don't find natural to have a separate repository, because the debian folder has to be at the root of the source. When working with repositories, this means I'd need to add locally `debian` symlinks from one repository to the other.
So, yes that's a little additional work on my side to update our CI setup, including the track/management of an additional repository.

I'd rather concede on removing the installer files. BTW, with an appropriate .gitignore file, the steps to clean up an imported upstream packaging could be skipped.

**Comment by vmaffione** [comment]
Ok, deal!

**Comment by jmuchemb** [comment]
> with an appropriate .gitignore file, the steps to clean up an imported upstream packaging could be skipped

To do this properly, I must rewrite the entire branch to merge.

Since the building steps for librina/rinad/rina-tools aren't so obvious, I guess I should also add a README.Debian file at the root.

I'll do all that this week-end, so do not merge before.

**Comment by vmaffione** [comment]
Yes, thanks!

**Comment by jmuchemb** [comment]
> To do this properly, I must rewrite the entire branch to merge.
> 
> Since the building steps for librina/rinad/rina-tools aren't so obvious, I guess I should also add a README.Debian file at the root.
> 
> I'll do all that this week-end, so do not merge before.

Finished. For me, it's ready to be merged.

No more `linux/debian/README.RINA` file. Everything is written in a `Debian-packaging.md` file at the root.

While testing the build of packages, I found a regression in 91934e3f05f3447a8ec739e2ff9286180d791f1a, where I left a comment.

**Comment by msune** [comment]
You can try using checkinstall to automate deb package generation from
autotools enviornment.

As a reference:

https://github.com/bisdn/xdpd/blob/stable/tools/deb/checkinstall_gen.sh

**Comment by jmuchemb** [comment]
In this PR, there is much more work that what checkinstall would be able to do.
That would not be usable the for the kernel, and the build-deps are even more important than we also automate the installation of requirements.

**Comment by msune** [comment]
As I said, checkinstall is to be used by autotools packages only. Linux
build system is not autotools. It was just a heads up. It all boils down on
which is easier to maintain, by others specially.

**Pull request merged**
