### PR TITLE
rinad: fix segfault when enrollment fails, fix #872

### LINKED ISSUE #872: Pristine-1.4: Segmentation fault after unsuccessful enrollment
After unsuccessful enrollment between 2 machines, but not always (I still don't know why), it's possible for the ipc process to generate a Segmentation Fault which cause the ipcp to be killed.

Gdb trace:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f7beeffd700 (LWP 1421)]
rina::cdap::ConnectionStateMachine::checkRelease (this=0x0) at /pristine/librina/src/cdap_v2.cc:1007
1007            lock();
```

I'm trying to get more info out of this problem, and I'll append a message with the bigger report eventually.

### PR DESCRIPTION
**Pull request by edugrasa**
@jmuchemb could you give it a try? I've tested the case when the member IPCP doesn't know the address of the IPCP that joins (in enrollment) and works for me

### CODE REVIEW

**Comment by jmuchemb** [comment]
I could not try immediately and it took me a while to check some things.

At first glance, I didn't see any guarantee that the scheduled task would run after `EnrollerStateMachine::start` has returned. That looked good enough for the moment (it's unlikely to take more than 10ms), but that would not be reliable on the long term.

Before I start to test your patch, I arranged it to reschedule the task as long as `EnrollerStateMachine::lock_` is locked. The good thing is that `EnrollmentFailedTimerTask & AbortEnrollmentTimerTask` could even be merged into a single class. See jmuchemb/irati-stack@67d29493c3fa8613975b720a8b021cff1fff5c69. But this was prematurate.

With only this PR, I still have too many issues.

I added 2 LOG_INFO to your code (one at the end of `IEnrollmentStateMachine::abortEnrollment` and another at the beginning of `AbortEnrollmentTimerTask::run`). Here is 1 crash (the first 2 numbers are pid & tid):
```
1980.1985(2016-10-05 12:41:00.6220)#ipcp (INFO): IEnrollmentStateMachine::abortEnrollment
1980.1985(2016-10-05 12:41:00.6220)#librina.syscalls (DBG): Invoking SYS_readManagementSDU (329)
1980.2006(2016-10-05 12:41:01.1173)#ipcp (INFO): AbortEnrollmentTimerTask::run
1980.2006(2016-10-05 12:41:01.1175)#ipcp[2].enrollment-task (ERR): An error happened during enrollment of remote IPC Process re6st.2.16-1-Management- because of Could not assign a valid address
1980.2006(2016-10-05 12:41:01.1176)#ipcp[2].enrollment-task (DBG): Removing enrollment state machine associated to 1
1980.2006(2016-10-05 12:41:01.1177)#librina.timer (DBG): Waiting for the timer 402665552 to join
1980.1985(2016-10-05 12:41:01.1331)#ipcp[2].rib-daemon (DBG): Received CDAP message from N-1 port 1 
Opcode: 2_M_RELEASE
Flags: 0
Invoke id: 2

1980.1985(2016-10-05 12:41:01.1332)#ipcp (DBG): M_RELEASE cdapMessage from portId 1
1980.1985(2016-10-05 12:41:01.1333)#ipcp[2].enrollment-task (DBG): Removing enrollment state machine associated to 1
1980.1985(2016-10-05 12:41:01.1333)#ipcp[2] (CRIT): Got signal 11
1980.1985(2016-10-05 12:41:01.1334)#rinad-debug (DBG): Cannot dump a backtrace
1980.1984(2016-10-05 12:41:01.1340)#librina.nl-manager (DBG): NL msg RX. Fam: 22; Opcode: 50_APP_FLOW_DEALLOC_NOT; Sport: 1; Dport: 1980; Seqnum: 0; Notification; SIPCP: 0; DIPCP: 2 
1980.1984(2016-10-05 12:41:01.1341)#librina.core (DBG): Added event of type 6_FLOW_DEALLOCATED and sequence number 0 to events queue
1980.1980(2016-10-05 12:41:01.1343)#ipcp[2].core (DBG): Got event of type 6_FLOW_DEALLOCATED and sequence number 0
1980.1980(2016-10-05 12:41:01.1344)#ipcp[2] (CRIT): Got signal 11
1980.1980(2016-10-05 12:41:01.1344)#rinad-debug (DBG): Cannot dump a backtrace
1980.1985(2016-10-05 12:41:01.1345)#librina.nl-manager (DBG): Netlink Manager destructor called
1980.1980(2016-10-05 12:41:01.1368)#ipcp[2] (CRIT): Got signal 2
1980.2006(2016-10-05 12:41:01.6176)#librina.timer (DBG): Timer with ID 402665552 ended
1980.2006(2016-10-05 12:41:01.6180)#ipcp[2].enrollment-task (ERR): Problems closing application connection: Cannot close a connection because this CDAP session is currently in 3 state
1980.2006(2016-10-05 12:41:01.6181)#ipcp[2].enrollment-task (ERR): Problems deallocating N-1 flow: <A0><8A>i
2014.2014(2016-10-05 12:41:03.6073)#librina.logs (DBG): New log level: DBG
```
Traceback:
```
Thread 3 "ipcp" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f92f67de700 (LWP 2792)]
0x00007f92f8930a84 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x00007f92f8930a84 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f92f93b892f in rina::Lockable::lock (this=this@entry=0x1d8) at /root/stack/librina/src/concurrency.cc:423
#2  0x000000000042fde5 in rina::ScopedLock::ScopedLock (lock=true, guarded=..., this=0x7f92f67dd720) at /usr/include/librina/concurrency.h:201
#3  rinad::IEnrollmentStateMachine::release (this=this@entry=0x0, invoke_id=invoke_id@entry=22, con_handle=...) at /root/stack/rinad/src/ipcp/enrollment-task.cc:460
#4  0x000000000042ff08 in rinad::EnrollmentTask::release (this=0x6a1660, invoke_id=22, con_handle=...) at /root/stack/rinad/src/ipcp/enrollment-task.cc:1214
#5  0x00007f92f93f3ecc in rina::rib::RIBDaemon::close_connection (this=0x6a2640, con=..., flags=..., invoke_id=22) at /root/stack/librina/src/rib_v2.cc:2540
#6  0x000000000042b103 in rinad::IPCPCDAPIOHandler::invoke_callback (this=this@entry=0x6a2940, con_handle=..., m_rcv=..., is_auth_message=is_auth_message@entry=false) at /root/stack/rinad/src/ipcp/rib-daemon.cc:320
#7  0x000000000042befd in rinad::IPCPCDAPIOHandler::process_message (this=0x6a2940, message=..., handle=1, cdap_dest=<optimized out>) at /root/stack/rinad/src/ipcp/rib-daemon.cc:270
#8  0x000000000042aa10 in rinad::doManagementSDUReaderWork (arg=0x6a3a00) at /root/stack/rinad/src/ipcp/rib-daemon.cc:72
#9  0x00007f92f892e444 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#10 0x00007f92f7dd120d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

Also, sometimes, the scheduled task is not executed:
```
# grep 'IEnrollmentStateMachine::abortEnrollment\|AbortEnrollmentTimerTask::run' re6st.1.16-1.log
[...]
2340.2344(2016-10-05 12:41:50.6513)#ipcp (INFO): IEnrollmentStateMachine::abortEnrollment
2340.2365(2016-10-05 12:41:51.1448)#ipcp (INFO): AbortEnrollmentTimerTask::run
2366.2374(2016-10-05 12:41:55.6549)#ipcp (INFO): IEnrollmentStateMachine::abortEnrollment
2366.2374(2016-10-05 12:42:05.6683)#ipcp (INFO): IEnrollmentStateMachine::abortEnrollment
2366.2481(2016-10-05 12:42:06.1600)#ipcp (INFO): AbortEnrollmentTimerTask::run
[...]
```
No idea whether it's normal.

Test case:
- 3 VM: re6st.0.16 (address=1), re6st.1.16 (address=2), re6st.2.16 (address=3)
- for re6st.0.16 and re6st.1.16, address of re6st.2.16 is unknown

**Comment by edugrasa** [comment]
Hi @jmuchemb ,

The modifications you propose look better than my fix, have you tested them in your setup? Does it eliminate the seg faults always? If so, please submit a new PR and I'll merge it into pristine-1.5. Thanks!

**Comment by jmuchemb** [comment]
No, I have the same segfaults, that's why I didn't submit a PR. My changes _only_ try to fix the extremely rare case where the task is run before `EnrollerStateMachine::start` has returned. I mean that my code makes the same assumption than yours, i.e. that the objects to be freed are not used after `EnrollerStateMachine::start` has returned, which looks wrong.

In fact, all this may also be the sign that `EnrollmentFailedTimerTask` has the same issue, if the doManagementSDUReaderWork thread may use the state machine at any time (e.g. `EnrollmentTask::release`).

I tried something else, in a way similar to `EnrollerStateMachine::connect`, i.e. releasing the lock just before aborting enrollment. Doing it only in `EnrollerStateMachine::start` is not enough. For example, I got `(CRIT): Cannot destroy mutex` at:
```
#0  rina::Lockable::~Lockable (this=<optimized out>, __in_chrg=<optimized out>) at /root/stack/librina/src/concurrency.cc:418
#1  0x0000000000436235 in rinad::IEnrollmentStateMachine::~IEnrollmentStateMachine (this=0x6afc70, __in_chrg=<optimized out>) at /root/stack/rinad/src/ipcp/enrollment-task.cc:402
#2  0x00007f1140a86b87 in rinad::BaseEnrollmentStateMachine::~BaseEnrollmentStateMachine (this=0x6afc70, __in_chrg=<optimized out>) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:69
#3  rinad::EnrolleeStateMachine::~EnrolleeStateMachine (this=0x6afc70, __in_chrg=<optimized out>) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:230
#4  rinad::EnrolleeStateMachine::~EnrolleeStateMachine (this=0x6afc70, __in_chrg=<optimized out>) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:230
#5  0x000000000042d176 in rinad::EnrollmentTask::enrollmentFailed (this=0x69f400, remotePeerNamingInfo=..., portId=3, reason=..., sendReleaseMessage=<optimized out>) at /root/stack/rinad/src/ipcp/enrollment-task.cc:1100
#6  0x00007f1140a81031 in rinad::EnrolleeStateMachine::remoteStartResult (this=0x6afc70, con_handle=..., obj=..., res=...) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:536
#7  0x00007f11440ba522 in rina::rib::RIBDaemon::remote_start_result (this=<optimized out>, con=..., obj=..., res=..., invoke_id=<optimized out>) at /root/stack/librina/src/rib_v2.cc:2945
#8  0x000000000042a32a in rinad::IPCPCDAPIOHandler::invoke_callback (this=this@entry=0x6a06e0, con_handle=..., m_rcv=..., is_auth_message=is_auth_message@entry=false) at /root/stack/rinad/src/ipcp/rib-daemon.cc:415
#9  0x000000000042b34d in rinad::IPCPCDAPIOHandler::process_message (this=0x6a06e0, message=..., handle=3, cdap_dest=<optimized out>) at /root/stack/rinad/src/ipcp/rib-daemon.cc:269
#10 0x0000000000429e70 in rinad::doManagementSDUReaderWork (arg=0x6a17a0) at /root/stack/rinad/src/ipcp/rib-daemon.cc:71
#11 0x00007f11435f2444 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#12 0x00007f1142a9520d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

I did the same thing in a few other methods: you can see the result at jmuchemb/irati-stack@1325dd3bcf70fcc648e1e2aedf6b849f22dff568. I have much fewer crashes than with this PR but it's not perfect: once, I got the same segfault as for `EnrollmentTask::release` (in my previous comment). Maybe a race condition with another thread aborting enrollment. This approach also seems  wrong.

`IEnrollmentStateMachine::lock_` looks strange to me. It would protect `state_` (at least), but `abortEnrollment` touches it without owning the lock. And it particular, a lock can't protect the deletion of the owning object (here, the state machine).

**Comment by edugrasa** [comment]
Hi Julien,

I'll take a look during the weekend, rethinking a bit how it is supposed to
work based on your feedbak. Thanks!

2016-10-06 19:35 GMT+02:00 Julien Muchembled <notifications@github.com>:

**Comment by edugrasa** [comment]
New PR issued, could you give it a try?

https://github.com/IRATI/stack/pull/1026

2016-10-06 20:37 GMT+02:00 Eduard Grasa Gras <eduard.grasa@i2cat.net>:

**Pull request merged**
