### PR TITLE
Mcr bug840

### PR DESCRIPTION
**Pull request by mcrotty**
Fixes error reporting.

### CODE REVIEW

**Comment by mcrotty** [comment]
@bernatgaston This will need your approval.

**Comment by bernatgaston** [comment]
Please fix the commit history. We can not have commits saying "Micheals temp fixes" or "Fix mistake" Use rebase to the last commit before your additions and make a single commit with the changes.

**Comment by bernatgaston** [comment]
ACK please @vmaffione merge this

**Comment by vmaffione** [comment]
too fast for me :)

**Pull request merged**
