### PR TITLE
kernel: shim-tcp-udp: improve cleanup, fix #575, fix #444

### LINKED ISSUE #444: Bad cleanup in the shim-tcp-udp if the UDP socket fails to bind
<a href="https://github.com/sandervrijders"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Tuesday Jan 27, 2015 at 16:12 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/441_

----

oopsvm

Attached a screenshot, since I got this in a VM. Happens after closing the IPCM in user-space. WIP branch.

### LINKED ISSUE #575: SHIM TCP cleaning
When destroying a shim tcp-udp ipcp, it does not unregister applications and sockets are not closed. When you try to run again and register one applications it fails

May  8 17:12:22 irati-vm kernel: [ 1781.787280] rina-pidm(DBG): Bitmap allocation completed successfully (id = 74)
May  8 17:12:22 irati-vm kernel: [ 1781.798632] rina-rmem(DBG): generic_alloc(16) = dfe0a9b0
May  8 17:12:22 irati-vm kernel: [ 1781.804757] rina-shim-tcp-udp(DBG): I'm in tcp_udp_flow_allocate_request (net/rina/ipcps/shim-tcp-udp.c:498)
May  8 17:12:22 irati-vm kernel: [ 1781.811719] rina-shim-tcp-udp(DBG): I'm in find_flow_by_port (net/rina/ipcps/shim-tcp-udp.c:245)
May  8 17:12:22 irati-vm kernel: [ 1781.816732] rina-rmem(DBG): generic_alloc(64) = f605cb00
May  8 17:12:22 irati-vm kernel: [ 1781.820563] rina-shim-tcp-udp(DBG): Allocate request flow added
May  8 17:12:22 irati-vm kernel: [ 1781.824197] rina-ipcp-utils(DBG): No flags, name comparison will be meaningless ...
May  8 17:12:22 irati-vm kernel: [ 1781.828882] rina-shim-tcp-udp(DBG): Directory entry found
May  8 17:12:22 irati-vm kernel: [ 1781.832211] rina-shim-tcp-udp(DBG): Max allowable gap is 0
May  8 17:12:22 irati-vm kernel: [ 1781.835798] rina-shim-tcp-udp(DBG): Reliable flow requested
May  8 17:12:22 irati-vm kernel: [ 1781.839855] rina-shim-tcp-udp(ERR): Could not connect TCP socket
May  8 17:12:22 irati-vm kernel: [ 1781.844965] rina-shim-tcp-udp(DBG): I'm in unbind_and_destroy_flow (net/rina/ipcps/shim-tcp-udp.c:405)

### PR DESCRIPTION
**Pull request by edugrasa**
Maintainers: @sandervrijders

### CODE REVIEW

**Comment by dstaesse** [comment]
while you are at it, can you fix this?
https://github.com/IRATI/stack/blame/master/linux/net/rina/ipcps/shim-tcp-udp.c#L569

it's the reason why it doesn't select UDP.

**Comment by edugrasa** [comment]
Done! rina-tgen also crashes with UDP, I think it is an issue with the workqueue locking (not related to TCP or UDP), therefore I wouldn't remove TCP since it is working the same way as UDP is.

**Comment by dstaesse** [comment]
I would first have a look at getting the UDP functions stable. We can flag the TCP support as "experimental", as it's not really essential to the project.

**Comment by dstaesse** [comment]
btw, did you ride that gravity wave yesterday? you're in the future again ;)

**Comment by edugrasa** [comment]
hehe, I forgot to sync the development server with ntp.. fixed!

**Comment by sandervrijders** [comment]
ACK

**Pull request merged**
