### PR TITLE
Pristine 1.3: TCP-RED Policy set

### PR DESCRIPTION
**Pull request by lbergesio**
This policy sets implements the RED algorithm in the RMT and a TCP-Tahoe-like congestion avoidance control in the DTCP. 

Maintainers:

@msune :
MAINTAINERS

@edugrasa :
librina/include/librina/configuration.h
librina/src/configuration.cc

@lbergesio :
linux/net/rina/dtcp.c
linux/net/rina/dtcp.h
linux/net/rina/dtp.c
plugins/red/*

@miqueltarzan 
linux/net/rina/rmt.c
linux/net/rina/rmt.h

### CODE REVIEW

**Comment by edugrasa** [comment]
ACK for the files I maintain.

**Comment by sandervrijders** [comment]
NACK, RMT files no longer pass checkpatch.pl

**Comment by edugrasa** [comment]
ACK testing the functionality; tried the usual tests (normal with 3 IPCPs over shim, 4 parallel rina-tgen clients agains the same rina-tgen server).

**Comment by edugrasa** [comment]
Tested again with 10 rina-tgen parallel flows and this setup https://wiki.ict-pristine.eu/WP6/d62/d62-trials-resilient-acc#Experiment-1:-Two-hosts-experiment (normal over normal), works fine (flows share the bottleneck BW, in this case 20 Mbps).

Checkpatch.pl is working now, if @miqueltarzan acks it I will merge the PR.

```
28809(1443024416)#traffic-generator (INFO): Port   22:       156 SDUs (      218400 bytes) in      1000863 us =>  155.8655 p/s,    1.7457 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   22:      4749 SDUs,      6648600 bytes in     30000 ms, 1.7730 Mb/s
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 22]
28809(1443024416)#traffic-generator (INFO): Port   23:       178 SDUs (      249200 bytes) in      1041625 us =>  170.8868 p/s,    1.9139 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   23:      4786 SDUs,      6700400 bytes in     30041 ms, 1.7843 Mb/s
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 23]
28809(1443024416)#traffic-generator (INFO): Port   26:       198 SDUs (      277200 bytes) in      1037835 us =>  190.7818 p/s,    2.1368 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   26:      4536 SDUs,      6350400 bytes in     30037 ms, 1.6914 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   24:       153 SDUs (      214200 bytes) in      1089044 us =>  140.4902 p/s,    1.5735 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   24:      4844 SDUs,      6781600 bytes in     30089 ms, 1.8031 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   25:       123 SDUs (      172200 bytes) in      1088504 us =>  112.9991 p/s,    1.2656 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   25:      4478 SDUs,      6269200 bytes in     30088 ms, 1.6669 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   27:       174 SDUs (      243600 bytes) in      1035569 us =>  168.0236 p/s,    1.8819 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   27:      5231 SDUs,      7323400 bytes in     30035 ms, 1.9506 Mb/s
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 24]
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 25]
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 27]
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 26]
28809(1443024416)#traffic-generator (INFO): Port   28:       204 SDUs (      285600 bytes) in      1026410 us =>  198.7510 p/s,    2.2260 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   28:      4889 SDUs,      6844600 bytes in     30026 ms, 1.8236 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   30:       148 SDUs (      207200 bytes) in      1027307 us =>  144.0660 p/s,    1.6135 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   30:      4416 SDUs,      6182400 bytes in     30027 ms, 1.6472 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   29:       144 SDUs (      201600 bytes) in      1028119 us =>  140.0616 p/s,    1.5687 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   29:      5183 SDUs,      7256200 bytes in     30076 ms, 1.9301 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   31:       161 SDUs (      225400 bytes) in      1073922 us =>  149.9178 p/s,    1.6791 Mb/s
28809(1443024416)#traffic-generator (INFO): Port   31:      4303 SDUs,      6024200 bytes in     30073 ms, 1.6026 Mb/s
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 28]
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 30]
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 29]
28809(1443024416)#traffic-generator (INFO): Flow torn down remotely [port-id = 31]

**Comment by miqueltarzan** [comment]
ACK

**Pull request merged**
