### PR TITLE
Implementation of LFA algorithm in user space

### PR DESCRIPTION
**Pull request by vmaffione**
Introduced support for Loop Free Alternate resiliency algorithm, that can be executed in addition to the normal shortest path algorithm. The purpose is to find LFA (neighbor) nodes for all the non-neigbhor destination nodes. More information can be found on D4.2 and D4.3 PRISTINE deliverables.

The resiliency algorithm is currently always disabled. Future pull request will allow the algorithm to be enabled depending on configuration file provided.

### CODE REVIEW

**Comment by vmaffione** [comment]
Waiting for ACK by
@edugrasa 
@lbergesio 
@bernatgaston

**Comment by bernatgaston** [comment]
ack

**Comment by edugrasa** [comment]
ack

**Comment by lbergesio** [comment]
ack

**Pull request merged**
