### PR TITLE
Changes in the serialized object for better swog bindings

### PR DESCRIPTION
**Pull request by bernatgaston**
Fioxed a librina swigg issue for MAD-Manager integration

### CODE REVIEW

**Comment by vmaffione** [comment]
Could you please explain what is the point in this change?

**Comment by bernatgaston** [comment]
by default. SWIG binds char* c++ to String in Java. This binding, which is usually good, is not suitable for all situations. In the specific case of the serialized object, char* means an array of bytes which is byte[] in java and not String. However, its very difficult to change (and maintain) only this special type binding in this specific occurence using SWIGG. Instead of this, void* is directly binded to byte[] so using this solution fewer changes must be done.

**Comment by mcrotty** [comment]
Bernat, there is a larger set of files affected by this change.  How submits the further pull request.

**Comment by bernatgaston** [comment]
If we used void* instead of char* bindings are automatically done to byte[] and moreover, few files need to be changed. I would go for this option.

**Pull request merged**
