### PR TITLE
Librina test fix

### LINKED ISSUE #666: Tests failing
Various tests at librina and rinad are failing

### PR DESCRIPTION
**Pull request by bernatgaston**
Fixed librina tests fixes #666

### CODE REVIEW

**Comment by bernatgaston** [comment]
After merge please close #666, I forgot to do that in the commit message

**Comment by bernatgaston** [comment]
After merge please close #666, I forgot to do that in the commit message

**Comment by vmaffione** [comment]
This can go in only after #662, since it includes the latter.

**Comment by edugrasa** [comment]
@bernatgaston you have to add the list of maintainers that have to ACK to the pull request description

**Comment by bernatgaston** [comment]
@edugrasa please ack concurrency and syscalls test

**Comment by edugrasa** [comment]
ACK, verified working

**Pull request merged**
