### PR TITLE
Fix rinad tests

### LINKED ISSUE #852: Tests in rinad not working
There has been one or more PR that have brokern the rinad tests

### PR DESCRIPTION
**Pull request by bernatgaston**
Fixes #852. A previous commit 2718f6ece0bf8b6462439a8695e5d3fc4f1ad52e
broke the rinad tests
ack @vmaffione

### CODE REVIEW

**Comment by vmaffione** [comment]
I still get an error

````
/bin/sh ../../libtool  --tag=CXX   --mode=link g++  -g -O2   -o test-encoders test_encoders-test-encoders.o test_encoders-components.o test_encoders-ipc-process.o test_encoders-namespace-manager.o test_encoders-flow-allocator.o test_encoders-enrollment-task.o test_encoders-resource-allocator.o test_encoders-rib-daemon.o test_encoders-routing.o test_encoders-security-manager.o ./../common/librinad.la -L/home/vmaffione/irati/local/lib -lrina -lnl-genl-3 -lnl-3 -lprotobuf -pthread -lpthread 
libtool: link: g++ -g -O2 -o .libs/test-encoders test_encoders-test-encoders.o test_encoders-components.o test_encoders-ipc-process.o test_encoders-namespace-manager.o test_encoders-flow-allocator.o test_encoders-enrollment-task.o test_encoders-resource-allocator.o test_encoders-rib-daemon.o test_encoders-routing.o test_encoders-security-manager.o -pthread  ./../common/.libs/librinad.so -L/home/vmaffione/irati/local/lib -Lencoders /home/vmaffione/irati/local/lib/librina.so -lssl -lcrypto /home/vmaffione/irati/local/lib/librinajsoncpp.so -ldl -lnl-genl-3 -lnl-3 -lprotobuf -lpthread -pthread -Wl,-rpath -Wl,/home/vmaffione/irati/local/lib
test_encoders-flow-allocator.o: In function `rinad::FlowAllocatorInstance::sync_with_kernel()':
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../flow-allocator.cc:1262: undefined reference to `rinad::SysfsHelper::get_dtp_tx_bytes(int, int, unsigned long&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../flow-allocator.cc:1265: undefined reference to `rinad::SysfsHelper::get_dtp_rx_bytes(int, int, unsigned long&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../flow-allocator.cc:1268: undefined reference to `rinad::SysfsHelper::get_dtp_tx_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../flow-allocator.cc:1271: undefined reference to `rinad::SysfsHelper::get_dtp_rx_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../flow-allocator.cc:1274: undefined reference to `rinad::SysfsHelper::get_dtp_drop_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../flow-allocator.cc:1277: undefined reference to `rinad::SysfsHelper::get_dtp_error_pdus(int, int, unsigned int&)'
test_encoders-resource-allocator.o: In function `rinad::RMTN1Flow::sync_with_kernel()':
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../resource-allocator.cc:111: undefined reference to `rinad::SysfsHelper::get_rmt_queued_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../resource-allocator.cc:112: undefined reference to `rinad::SysfsHelper::get_rmt_drop_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../resource-allocator.cc:113: undefined reference to `rinad::SysfsHelper::get_rmt_error_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../resource-allocator.cc:114: undefined reference to `rinad::SysfsHelper::get_rmt_rx_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../resource-allocator.cc:115: undefined reference to `rinad::SysfsHelper::get_rmt_tx_pdus(int, int, unsigned int&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../resource-allocator.cc:116: undefined reference to `rinad::SysfsHelper::get_rmt_rx_bytes(int, int, unsigned long&)'
/home/vmaffione/irati/rinad/src/ipcp/plugins/default/../../resource-allocator.cc:117: undefined reference to `rinad::SysfsHelper::get_rmt_tx_bytes(int, int, unsigned long&)'
collect2: error: ld returned 1 exit status
Makefile:801: recipe for target 'test-encoders' failed
make[5]: *** [test-encoders] Error 1
make[5]: Leaving directory '/home/vmaffione/irati/build/rinad/src/ipcp'
Makefile:1551: recipe for target 'check-am' failed
make[4]: *** [check-am] Error 2
make[4]: Leaving directory '/home/vmaffione/irati/build/rinad/src/ipcp'
Makefile:1240: recipe for target 'check-recursive' failed
make[3]: *** [check-recursive] Error 1
make[3]: Leaving directory '/home/vmaffione/irati/build/rinad/src/ipcp'
Makefile:406: recipe for target 'check-recursive' failed
make[2]: *** [check-recursive] Error 1
make[2]: Leaving directory '/home/vmaffione/irati/build/rinad/src'
Makefile:441: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/home/vmaffione/irati/build/rinad'
Makefile:733: recipe for target 'check' failed
make: *** [check] Error 2
````

**Comment by vmaffione** [comment]
Please check https://github.com/bernatgaston/stack/pull/33

**Comment by bernatgaston** [comment]
It is working for me, have you intalled from scratch first? This problem you are reporting is due to missing links in the makefile project so it needs an install from scratch (at least the user part) to work

**Comment by vmaffione** [comment]
Yes, tried to install from scratch. This https://github.com/bernatgaston/stack/pull/33 is necessary for it to work.

**Comment by bernatgaston** [comment]
Yes but I already merged, the branch should cvontain your changes and should be working now

**Comment by vmaffione** [comment]
Yes it is working. My message "I still get an error" was referred to the code before the fix I proposed.

**Comment by bernatgaston** [comment]
Ok, thanks

**Pull request merged**
