### PR TITLE
5.10 fixes

### PR DESCRIPTION
**Pull request by fdgonthier**
This fixes compilation of the IRATI kernel modules for Linux 5.10 kernel

This is just an RFC PR as this is **untested**. The patch is enough for the modules to compile and load but I I do not know how to configure my sample RINA setup with encryption so that this code path get used. Suggestion are welcome.

### CODE REVIEW

**Comment by TRIA** [comment]
The CI failures are on kernels 4.1 and 4.2, which had not yet incorporated the new crypto API.  Those kernels are ancient, and could be removed from the CI with little loss.

**Comment by edugrasa** [comment]
Hi, 

Thanks for the fix proposal! However it does not comply with the practice we have been following to support multiple kernel version (which is not written anywhere, I know and sorry for that :) ).

The trick is to use #if, #else, #endif primitives that take into account the kernel version, like in https://github.com/IRATI/stack/blob/master/kernel/ipcps/shim-tcp-udp.c#L724

Could you update your pull request so that the new code you added gets used for versions 4.3 up and the old code for versions 4.2 down? Thanks a lot!

**Comment by fdgonthier** [comment]
Alright, I will update the code, no problem.

But I would also like to know how to test this feature. I couldn't find any configuration example about this.

**Comment by edugrasa** [comment]
Hi,

You can use the tutorial in https://github.com/IRATI/stack/wiki/Tutorial-3:-Security-provider-net to test this feature. You don't need to deploy the whole scenario depicted in the tutorial, it will be enough with the red DIF (access. DIF) and the "Customer border Router" and "Provider border router 1" systems (so a couple of VMs are enough for testing this).

Cheers,

Eduard

**Comment by edugrasa** [comment]
Closing this PR. The code to support 5.5+ kernels has been already merged in; in case something does not work please let me now :)

**Pull request closed without merging**
