### PR TITLE
ipcm: dif-template-manger: filter by file name suffix

### LINKED ISSUE #600: dif-template-manager: remove hardcoded file names and extensions
These hardcoded things

https://github.com/IRATI/stack/blob/c932c86eff1661fd037536b44e888d5840f77591/rinad/src/ipcm/dif-template-manager.cc#L90-L99

have to go away.

If we have to resort to this approach to make things work it means that something is wrong in the approach - imho.

### PR DESCRIPTION
**Pull request by vmaffione**
Fixes #600 https://github.com/IRATI/stack/issues/600

### CODE REVIEW

**Comment by edugrasa** [comment]
But you can also remove the checks for *.swp, etc from process_events, can't you?

**Comment by vmaffione** [comment]
For sure I can remove the ".swp" and ".swx" and "4913". Don't know if the tilde "~" one is needed.
Can it happen that you have some temp file named "~mywonderdif.dif"?

**Comment by sandervrijders** [comment]
Nay, emacs generates mywonderdif.dif~ instead of ~mywonderdif.dif

**Comment by vmaffione** [comment]
Done, please give a look at it.

**Comment by edugrasa** [comment]
ACk!

**Pull request merged**
