### PR TITLE
First implementation of the POSIX API

### PR DESCRIPTION
**Pull request by vmaffione**
This work introduces an I/O device exposed by the kernel and a wrapper in librina to implement a POSIX-like RINA API (librina/wrap/rina-api/include/rina/api.h).

[POSIX-API-PR.pdf](https://github.com/IRATI/stack/files/606927/POSIX-API-PR.pdf)

@lbergesio @miqueltarzan @edugrasa @sandervrijders @dstaesse 

Missing items will be implemented using further pull requests:
  1) proper poll() implementation
  2) close() causes flow deallocation
  3) small fixes/addition to the API

### CODE REVIEW

**Comment by msune** [comment]
Bravo!!

**Comment by sandervrijders** [comment]
@vmaffione Why not deprecate the c-wrapper immediately as well?

**Comment by vmaffione** [comment]
@sandervrijders yes, indeed, I already ifdef'd it out. I can add a commit to just remove it.

**Comment by vmaffione** [comment]
API updated with the feedback received from the discussion of the Pisa meeting.

https://github.com/vmaffione/rlite/blob/master/include/rina/api.h

**Comment by edugrasa** [comment]
Tried to compile user-space from scratch but got this compilation error:

````
In file included from /root/openirati/librina/src/timer.cc:28:0:
/root/openirati/librina/include/librina/common.h:766:9: error: 'uint32_t' does not name a type
         uint32_t port_id;
````

**Comment by vmaffione** [comment]
Ok, can you please try again? I was not getting that error, probably because my toolchain is different.

**Comment by edugrasa** [comment]
Got past this error, but got another one:

````
/root/openirati/librina/src/cdap_v2.cc: In member function 'virtual void rina::cdap::AppCDAPIOHandler::send(const cdap_m_t&, const con_handle_t&)':
/root/openirati/librina/src/cdap_v2.cc:3574:21: error: 'errno' was not declared in this scope
                 if (errno != EAGAIN && errno != EINTR) {
````

**Comment by vmaffione** [comment]
Ok, please try again.

**Comment by edugrasa** [comment]
Ok, almost there! This is the compilation error now:

````
server.Tpo -c -o rina_cdap_echo-cdap-echo-server.o `test -f 'cdap-echo-server.cc' || echo '/root/openirati/rina-tools/src/rina-cdap-echo/'`cdap-echo-server.cc
In file included from /root/openirati/rina-tools/src/rina-cdap-echo/cdap-echo-server.cc:36:0:
/root/openirati/rina-tools/src/rina-cdap-echo/cdap-echo-server.cc: In member function 'void CDAPEchoWorker::serveEchoFlow()':
/root/openirati/rina-tools/src/rina-cdap-echo/cdap-echo-server.cc:119:75: error: 'errno' was not declared in this scope
                                                         port_id, strerror(errno));
                                                                           ^
/usr/local/irati/include/librina/logs.h:106:42: note: in definition of macro '__LOG'
                     getpid(), time(0), ##ARGS);                               \
                                          ^
/root/openirati/rina-tools/src/rina-cdap-echo/cdap-echo-server.cc:118:41: note: in expansion of macro 'LOG_ERR'
                                         LOG_ERR("Error while reading from flow %d [%s]",
                                         ^
compilation terminated due to -Wfatal-errors.
````

**Comment by vmaffione** [comment]
I tried to fix all the places in rina-tools. Can you try again?

**Comment by edugrasa** [comment]
Compilation works now, testing!

**Comment by vmaffione** [comment]
Good! For sure you can test the system in the usual way (so rina-echo-time, etc.).

But you also need to test the API itself: some applications are available here:

https://github.com/vmaffione/rlite/blob/master/user/tools/rinaperf.c 
https://github.com/vmaffione/rlite/blob/master/user/tools/rina-rr-tool.c

To compile them, you need to link them against the rina-api library, so add "-lrina-api"

**Comment by edugrasa** [comment]
Tried a local flow (normal IPCP) between a rina-echo-time server and client, but it didn't work. I've got this output at the rina-echo-time client:

````
root@e2-edu-vm3:/usr/local/irati/bin# ./rina-echo-time -c 100 -w 0
5651(1480524423)#librina.logs (DBG): New log level: INFO
5651(1480524423)#librina.nl-manager (INFO): Netlink socket connected to local port 5651 
5651(1480524423)#rina-echo-time (ERR): Cannot bind port id 1 on /dev/irati [Inappropriate ioctl for device]
````

And this output at the server (registration worked, but accepting the flow didn't)
````
root@e2-edu-vm3:/usr/local/irati/bin# ./rina-echo-time -l
5308(1480524395)#librina.logs (DBG): New log level: INFO
5308(1480524395)#librina.nl-manager (INFO): Netlink socket connected to local port 5308 
5308(1480524395)#rina-echo-time (INFO): Application registered in DIF 
5308(1480524424)#rina-echo-time (ERR): Cannot bind port id 2 on /dev/irati [Inappropriate ioctl for device]
````

**Comment by vmaffione** [comment]
Hi Eduard.
Are you sure you are recompiled and installed the kernel?
The same test works fine to me..
Can you try to recompile kernel first and userspace afterwards and retry?

**Comment by edugrasa** [comment]
Yeap! Tried again with the same result. Maybe the problem is if the flow is through a local IPCP?

**Comment by vmaffione** [comment]
Ah I have never tried a local flow.
Can you try with a non-local flow, while I take a look at what happens with local flows?

**Comment by edugrasa** [comment]
Tried again, when the IPCP enrolls and allocates an N-1 flow, same problem happens:

````
3578(1480591263)#librina.ipc-manager (DBG): ApplicationManager::flowAllocated called
3578(1480591263)#librina.nl-manager (DBG): NL msg TX. Fam: 25; Opcode: 45_APP_ALLOC_FLOW_REQ_RES; Sport: 1; Dport: 3583; Seqnum: 1480591213; Response; SIPCP: 0; DIPCP: 2
3578(1480591263)#ipcm.flow-alloc (INFO)[ipcm_allocate_flow_request_result_handler]: Applications B.IRATI:1:: and A.IRATI:1:: informed about flow allocation result

3583(1480591263)#librina.nl-manager (DBG): NL msg RX. Fam: 25; Opcode: 45_APP_ALLOC_FLOW_REQ_RES; Sport: 1; Dport: 3583; Seqnum: 1480591213; Response; SIPCP: 0; DIPCP: 2 
3583(1480591263)#librina.core (DBG): Added event of type 1_ALLOCATE_FLOW_REQUEST_RESULT and sequence number 1480591213 to events queue
3583(1480591263)#ipcp[2].ipc-process (DBG): Got event of type 1_ALLOCATE_FLOW_REQUEST_RESULT and sequence number 1480591213
3583(1480591263)#ipcp[2] (ERR): Problems running event loop: Cannot bind port id 1 on /dev/irati [Inappropriate ioctl for device]
````
Maybe I have something wrong? I just installed from scratch your branch and rebooted. I can see the /dev/irati device exists.. 

````
root@e2-edu-vm2:/usr/local/irati/bin# ls -l /dev/irati
crw------- 1 root root 10, 57 Dec  1  2016 /dev/irati 
````

**Comment by vmaffione** [comment]
mmm, what does the kernel log say regarding that ioctl()?

**Comment by vmaffione** [comment]
maybe it's unrelated, but can you try to first
````
# chmod a+rw /dev/irati
````

**Comment by edugrasa** [comment]
Yeah, seems to be unrelated, tried what you said and I get the same error. No kernel logs.

**Comment by vmaffione** [comment]
what about the kernel headers ?
However, from your descriptioin it seems that for some reason you are issuing ioctl() on a bogus file descriptor..

**Comment by edugrasa** [comment]
Issues are gone after the latest changes :)

**Comment by vmaffione** [comment]
Thanks for testing! Regarding the weird problem related to the ioctl() cmd, could give a try to the "api-bis" branch that I just pushed to my fork?

**Comment by vmaffione** [comment]
Thanks for testing! Regarding the weird problem related to the ioctl() cmd, could give a try to the "api-bis" branch that I just pushed to my fork?

**Comment by edugrasa** [comment]
Strange as it may seem the api-bis branch doesn't work for me .. same problems as before

**Comment by vmaffione** [comment]
Can you describe exactly what kind of machine you are compiling (and testing on)? Is that a virtual machine or physical? Is that 32-bits or 64 bits?

In any case, I've updated the api-bis branch (you need to reset the branch, not just merge), can you retry it again?

**Comment by edugrasa** [comment]
It is a XEN VM, here's the output of "uname -a". The api-bis branch works now!

````
Linux e2-edu-vm2 4.1.33 #94 SMP Thu Dec 1 10:18:31 CET 2016 x86_64 GNU/Linux
````

**Comment by vmaffione** [comment]
Ok, so the problem was either the compatibility layer between 32 applications and 64 bits kernel or a conflict with another command. I will now merge api-bis into api, try to put rlite tools into rina-tools, and let you know.

**Comment by vmaffione** [comment]
Example applications "rinaperf" and "rina-echo" (using the new API) integrated into rina-tools.
@edugrasa can you test?

**Comment by edugrasa** [comment]
Works fine, ACK!

**Pull request merged**
