### PR TITLE
Refactor of kernel flow allocator

### PR DESCRIPTION
**Pull request by dstaesse**
kfa.[c/h] : refactored code to comply with kernel guidelines

maintainer: @miqueltarzan

### CODE REVIEW

**Comment by dstaesse** [comment]
@miqueltarzan: while refactoring I saw two passages where there is a LOG_ERR followed by a return 0:
e.g.
```
	if ((atomic_read(&flow->readers) == 0) &&
	    (atomic_read(&flow->writers) == 0) &&
	    (atomic_read(&flow->posters) == 0)) {
		if (kfa_flow_destroy(instance, flow, id))
			LOG_ERR("Could not destroy the flow correctly");
		spin_unlock_irqrestore(&instance->lock, flags);
		return 0;
	}
```
I assume these are correct for the program flow, but it smells a bit fishy.

**Comment by vmaffione** [comment]
ACK, usual tests work

**Comment by vmaffione** [comment]
This is mostly coding-style fixes. @miqueltarzan , can we merge it?

**Comment by dstaesse** [comment]
@vmaffione: this PR contains coding-style fixes exclusively ;)
@miqueltarzan: can you have a quick look and ACK this?

```
dstaesse@m:~/stack/linux/net/rina$ ../../scripts/checkpatch.pl -f kfa.c
total: 0 errors, 0 warnings, 1120 lines checked

kfa.c has no obvious style problems and is ready for submission.

dstaesse@m:~/stack/linux/net/rina$ ../../scripts/checkpatch.pl -f kfa.h
total: 0 errors, 0 warnings, 75 lines checked

kfa.h has no obvious style problems and is ready for submission.
```

**Comment by miqueltarzan** [comment]
@dstaesse: I agree, the return value could be -1 instead of 0. The reason to choose the latter was that nothing else could be done if the KFA couldn't destroy the flow, and it wouldn't make any difference to the caller or the stack knowing that this failed.

ACK.

**Pull request merged**
