### PR TITLE
rina-tools: allow servers to register to multiple DIFs

### PR DESCRIPTION
**Pull request by edugrasa**
Using the "-d" option, it is possible to specify multiple DIF names separated by ";"

    ./rina-echo-time -l -d "normal.DIF;vpn.DIF;test.DIF"

@vmaffione could you give it a go?

### CODE REVIEW

**Comment by vmaffione** [comment]
yes, I will!

**Comment by vmaffione** [comment]
First we need to merge #971.

With that fix, I tried the following scenario:
````
# 300 is a shim-eth-vlan DIF (unlimited link speed) with nodes a and b
eth 300 0Mbps a b

# 400 is a shim-eth-vlan DIF (unlimited link speed), with nodes b and c
eth 400 0Mbps b c

# DIF n1 spans over A and B
dif n1 a 300
dif n1 b 300
# DIF n2 spans over B and C
dif n2 b 400
dif n2 c 400

````

I ran the server on node B
````
rina-echo-time -l -d n1.DIF;n2.DIF
````
which reports only the registration into n1.DIF (or the first in the list). And actually only A is able to reach the server, C is not.

````
vmaffione@b ~ >> irati/local/bin/rina-echo-time -l -d n1.DIF;n2.DIF
814(1467205509)#librina.logs (DBG): New log level: INFO
814(1467205509)#librina.nl-manager (INFO): Netlink socket connected to local port 814 
814(1467205509)#rina-echo-time (INFO): Application registered in DIF n1.DIF
^C
````

**Comment by edugrasa** [comment]
Have you tried with " "?

irati/local/bin/rina-echo-time -l -d "n1.DIF;n2.DIF"

**Comment by vmaffione** [comment]
You are right, it works indeed. I was fooled by the fact that the shell does not execute the command "n2.DIF", because of the control-C, so I didn't notice the problem.

This is really dangerous, we have to replace the ";" with something else, e.g. ","

**Comment by edugrasa** [comment]
Ok, will do!

**Comment by edugrasa** [comment]
Done, now the separator is ',', don't need to add " " anymore:

```
root@e2-edu-vm3:/usr/local/irati/bin# ./rina-echo-time -l -d normal.DIF,vpn.DIF
22673(1467213955)#librina.logs (DBG): New log level: INFO
22673(1467213955)#librina.nl-manager (INFO): Netlink socket connected to local port 22673 
22673(1467213955)#rina-echo-time (INFO): Application registered in DIF normal.DIF
22673(1467213955)#rina-echo-time (INFO): Application registered in DIF vpn.DIF
22673(1467213959)#rina-echo-app (INFO): New flow allocated [port-id = 2]

**Pull request merged**
