### PR TITLE
librina: Added bindings for C

### PR DESCRIPTION
**Pull request by dstaesse**
Adds a library for calling librina from C programs. It is required for the upcoming ioq3 port. The c bindings are installed by default, but can be disabled by passing the --disable-c-bindings flag to ./configure (librina).

Maintainers: @msune for MAINTAINERS file, @dstaesse for the rest. 
Makefiles seem missing from MAINTAINERS, probably should be checked by @edugrasa and @vmaffione.

### CODE REVIEW

**Comment by dstaesse** [comment]
The quickest way to test this PR is to install it userspace in /usr/local/irati, clone IRATI/ioq3 and run 'make' there. If everything compiles, this PR works.

**Comment by vmaffione** [comment]
@dstaesse I've tried to configure and compile librina, but I see that by default the c-bindings are not built. I have to explicitely pass --enable-c-bindings to build them.

**Comment by vmaffione** [comment]
And, if I include them:
````
make[4]: Entering directory '/home/vmaffione/irati/build/librina/wrap/c/src'
make[4]: *** No rule to make target 'librina-c.pc.in', needed by 'librina-c.pc'.  Stop.
make[4]: Leaving directory '/home/vmaffione/irati/build/librina/wrap/c/src'
Makefile:419: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/home/vmaffione/irati/build/librina/wrap/c'
Makefile:423: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/home/vmaffione/irati/build/librina/wrap'
Makefile:470: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/vmaffione/irati/build/librina'
Makefile:416: recipe for target 'all' failed
make: *** [all] Error 2
````
I think librina-c.pc.in is missing, you did not include it in the PR.

**Comment by dstaesse** [comment]
@vmaffione: how did you build? they should be enabled by default:
can you rm-rf your userspace build directory and try again?
```
+build_bindings_c=yes
```
librina-c.pc.in was untracked because of .gitignore
added and rebased commit

**Comment by vmaffione** [comment]
I built using install-user-from-scratch. I cannot try from home, don't have access to my VMs. WIll try on monday.

**Comment by dstaesse** [comment]
@vmaffione, Sander had the same issue that the c-bindings were indeed disabled by default. I have a fix, pushing in short.

**Comment by vmaffione** [comment]
Compilation of RINA-enhanced ioq3 works, but configure.ac is still broken.

If you don't specify --enable-c-bindings nor --disable-c-bindings, it compiles c-bindings in, which is correct.
If you specify --enable-c-bindings, it does not compile in c-bindings, which is wrong.
If you specify --disable-c-bindings, it does compile in c-bindings, which is wrong.

**Comment by dstaesse** [comment]
@vmaffione: yeah, sorry about that, I was messing up. Checked all cases thoroughly this time. Should really be fixed now.

**Comment by vmaffione** [comment]
ACK

**Comment by sandervrijders** [comment]
Seems ok to me. I could also compile ioq3 with RINA after I enabled C bindings

**Comment by dstaesse** [comment]
all cases now worked for me on a clean server. I think it's good to go in.

**Pull request merged**
