### PR TITLE
Pristine 1.3 shim eth size

### PR DESCRIPTION
**Pull request by edugrasa**
Added a check for max SDU size in shim-eth-vlan write (max size configurable via kconfig)

Maintainers:

@sandervrijders

### CODE REVIEW

**Comment by sandervrijders** [comment]
@edugrasa Isn't it possible to obtain this dynamically, from the device?

**Comment by edugrasa** [comment]
@sandervrijders fixed (getting mtu from netdevice)

**Comment by sandervrijders** [comment]
ACK

**Comment by sandervrijders** [comment]
ACK

**Pull request merged**
