### PR TITLE
Pristine 1.5 sdup

### PR DESCRIPTION
**Pull request by olichtne**
This pull request includes the updated SDU Protection crypto policy set and the new TLS inspired authentication policy from Eduard. The crypto policy set now does compression, sequence number checking, hmac, padding and encryption. The parameters for these operations can be set through the update_crypto_state netlink message.

I've tested with the authentication/sdu protection disabled, using ssh2 and authtls authentication policies.

'check_maintainers.py -l pristine-1.5' returns these names:
@miqueltarzan @edugrasa @lbergesio @vmaffione @msune 

And I think the MAINTAINERS file should be updated at least for the kernel sdu protection stuff since the dup-* files don't exist anymore and were replaced by sdup* files... But this comes up as a conflict with the sdu* regex that @vmaffione maintans.

### CODE REVIEW

**Comment by edugrasa** [comment]
ACK! Tried all configurations (auth-ssh, auth-tls, no auth) without detecting any problem.

**Comment by miqueltarzan** [comment]
ACK

**Comment by lbergesio** [comment]
ack

2016-07-07 14:04 GMT+02:00 miqueltarzan <notifications@github.com>:

> ACK
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/IRATI/stack/pull/973#issuecomment-231058834>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ABtu_AXSZJWGEcU09sD4GuWkaGJvWJWaks5qTOtggaJpZM4JGKil>
> .
>



-- 
Leonardo Bergesio
Distributed Applications and Networks Area - DANA
i2CAT Foundation - www.i2cat.net
C/ Gran Capità 2-4, office 109, Nexus I building
08034 Barcelona, Catalonia (Spain)
T: +34 93 567 9926
F: +34 93 553 2520
W: http://dana.i2cat.net

**Comment by vmaffione** [comment]
(forgot to) Ack, regression tests work properly

**Pull request merged**
