### PR TITLE
Connection struct made internal to EFCP. Connection policies replaced by DTP and DTCP config structs.

### LINKED ISSUE #264: Make 'connection' struct internal to EFCP
<a href="https://github.com/sandervrijders"></img></a> **Issue by [sandervrijders](https://github.com/sandervrijders)**
_Thursday Jan 16, 2014 at 13:35 GMT_
_Originally opened as https://github.com/dana-i2cat/irati/issues/261_

----

### PR DESCRIPTION
**Pull request by lbergesio**
Fixes #264 

The connection_policies struct has been replaced by dtp_config and dtcp_config structs which are then passed to the dtp/dtcp componenent. 

RNL updated and user space updated to these changes.

ACKs required from @miqueltarzan, @edugrasa, @vmaffione, @msune 

F: librina/include/librina/configuration.h
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: librina/include/librina/ipc-process.h
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: librina/src/configuration.cc
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: librina/src/ipc-process.cc
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: librina/src/netlink-parsers.cc
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: librina/src/netlink-parsers.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/connection.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/connection.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dt-utils.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtcp-conf-utils.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtcp-conf-utils.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtcp-ps-common.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtcp-utils.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtcp-utils.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtcp.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtcp.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtp-conf-utils.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtp-conf-utils.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtp-ps-common.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtp.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/dtp.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/efcp.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/efcp.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/ipcp-instances.h
	Vincenzo Maffione <v.maffione (at) nextworks.it>
F: linux/net/rina/ipcps/normal-ipcp.c
	Miquel Tarzan <miquel.tarzan (at) i2cat.net>
F: linux/net/rina/kipcm.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/rnl-utils.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/rnl-utils.h
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: linux/net/rina/rnl.c
	Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
F: rinad/src/common/encoder.cc
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: rinad/src/common/encoder.h
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: rinad/src/common/encoders/ConnectionPoliciesMessage.proto
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: rinad/src/common/encoders/FlowMessage.proto
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: rinad/src/common/encoders/QoSCubeMessage.proto
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: rinad/src/ipcm/configuration.cc
	Marc Sune <marc.sune (at) bisdn.de>
F: rinad/src/ipcp/flow-allocator.cc
	Eduard Grasa <eduard.grasa (at) i2cat.net>
	Eduard Grasa <eduard.grasa (at) i2cat.net>
F: rinad/src/ipcp/plugins/default/flow-allocator-ps.cc
	Eduard Grasa <eduard.grasa (at) i2cat.net>
	Eduard Grasa <eduard.grasa (at) i2cat.net>

### CODE REVIEW

**Comment by sandervrijders** [comment]
@lbergesio For the next commits, please follow the naming scheme we agreed upon.

**Comment by msune** [comment]
Agree with @sandervrijders 

Changes in rinad/src/ipcm/configuration.cc are trivial renamings, therefore ACK

**Comment by vmaffione** [comment]
Agree with @sandervrijders. Also we agreed to add a brief description to each commit, in addition to the commit message.

**Comment by vmaffione** [comment]
NAK, there is regression w.r.t. pristine-1.3 (tested).

I was doing the usual tests in the 3 nodes linear scenario (m1 -- m2 -- m3), and trying to let m1 communicate with m3.
First rina-echo-time ping is ok. Second time, after flow allocation terminates, packets are dropped on the sender, so communication does not work anymore.

````
[  149.871366] rina-dtp(ERR): PDU Dropped, counter inc
[  159.683111] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  159.684415] rina-rmt(ERR): EFCP container problems
[  159.685595] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  159.686849] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  159.688175] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  159.689465] rina-rmt(ERR): EFCP container problems
[  159.690679] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  159.692055] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  255.170562] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  255.172084] rina-rmt(ERR): EFCP container problems
[  255.173271] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  255.173848] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  255.173848] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  255.173848] rina-rmt(ERR): EFCP container problems
[  255.177111] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  255.178079] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  257.171272] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  257.172379] rina-rmt(ERR): EFCP container problems
[  257.173256] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  257.174193] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  257.174575] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  257.174575] rina-rmt(ERR): EFCP container problems
[  257.174575] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  257.174575] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  263.643476] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  263.644526] rina-rmt(ERR): EFCP container problems
[  263.645355] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  263.646280] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  263.647230] rina-efcp(ERR): Cannot find the requested instance cep-id: 0
[  263.648174] rina-rmt(ERR): EFCP container problems
[  263.649035] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  263.649968] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
````

**Comment by lbergesio** [comment]
Last 2 commits fixed the problem, which was a wrong allocation of the cep ids in the connection. Please recheck.

**Comment by vmaffione** [comment]
OK, The error disappeared.

**Comment by edugrasa** [comment]
ack

**Comment by miqueltarzan** [comment]
ACK

**Pull request merged**
