### PR TITLE
Robjects implementation to provide sysfs integration

### PR DESCRIPTION
**Pull request by lbergesio**
This PR implements the integration with sysfs in order to allow the kernel to export its internal state to monitoring function in user-space.

The following components in the kernel were integrated:
- IPCP instances (normal, shin-eth-vlan, shim-hv) ==> shim-tcp-udp missing
- Core, KIPCM, Factories
- EFCP, DTP, DTCP
- RMT, PFF, N-1 ports
- RMT and PFF default PSs ==> missing those in /plugins

Robjects implemented in rds/robjects.[ch] as a separate layer exporting RINA objects and APIs. 
Current Robjects and APIs are wrappers to kobjects+sysfs, but they provides some amount of independence if we decide to change this at some point in time. Moreover, they simplify the calls to the internal kobjects-sysfs systems providing one-line calls to perform just those actions required by IRATI.

Missing parts:
- Custom PS may be ported to robjects later on
- shim-tcp-udp integration

MAINTEINERS:

@msune 
F: MAINTAINERS

@edugrasa 
F: librina/include/librina/ipc-process.h
F: librina/src/ipc-process.cc
F: rinad/src/common/encoder.cc
F: rinad/src/ipcp/components.h
F: rinad/src/ipcp/flow-allocator.cc
F: rinad/src/ipcp/flow-allocator.h
F: rinad/src/ipcp/ipc-process.cc
F: rinad/src/ipcp/ipc-process.h
F: rinad/src/ipcp/resource-allocator.cc
F: rinad/src/ipcp/resource-allocator.h
F: rinad/src/ipcp/utils.cc
F: rinad/src/ipcp/utils.h

@vmaffione 
F: linux/net/rina/core.c
F: linux/net/rina/ipcp-factories.c
F: linux/net/rina/ipcp-factories.h
F: linux/net/rina/ipcp-instances.h
F: linux/net/rina/ipcps/shim-hv-core.c
F: linux/net/rina/pci.h
F: linux/net/rina/rds/robjects.c
F: linux/net/rina/rds/robjects.h
F: linux/net/rina/utils-workarounds.c
F: linux/net/rina/utils.h

@lbergesio ==> @vmaffione , @edugrasa @miqueltarzan 
F: linux/net/rina/dt-utils.c
F: linux/net/rina/dt-utils.h
F: linux/net/rina/dtcp-ps-default.c
F: linux/net/rina/dtcp.c
F: linux/net/rina/dtcp.h
F: linux/net/rina/dtp-ps-default.c
F: linux/net/rina/dtp.c
F: linux/net/rina/dtp.h
F: linux/net/rina/efcp.c
F: linux/net/rina/efcp.h
F: linux/net/rina/kipcm.c
F: linux/net/rina/kipcm.h

@miqueltarzan 
F: linux/net/rina/ipcps/normal-ipcp.c
F: linux/net/rina/rmt-ps-default.c
F: linux/net/rina/rmt.c
F: linux/net/rina/rmt.h

@sandervrijders 
F: linux/net/rina/ipcps/shim-eth-vlan-core.c
F: linux/net/rina/pff-ps-default.c
F: linux/net/rina/pff.c
F: linux/net/rina/pff.h
F: linux/net/rina/serdes.c
F: linux/net/rina/serdes.h

### CODE REVIEW

**Comment by lbergesio** [comment]
@guys, any comment on this one? and happy new year btw

**Comment by vmaffione** [comment]
I have to take a look, asap

**Comment by lbergesio** [comment]
Added a very basic integration of shim-tcp-udp to robjects. Once this is merged we need to discuss which information is needed for each shim ipcp and same thing for custom plugins.

**Comment by vmaffione** [comment]
Have you merged again from pristine-1.4 to include #836 ?

**Comment by lbergesio** [comment]
Now it is!

2016-01-18 18:08 GMT+01:00 Vincenzo Maffione <notifications@github.com>:

> Have you merged again from pristine-1.4 to include #836
> <https://github.com/IRATI/stack/pull/836> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/820#issuecomment-172593406>.
>



-- 
Leonardo Bergesio
Distributed Applications and Networks Area - DANA
i2CAT Foundation - www.i2cat.net
C/ Gran Capità 2-4, office 109, Nexus I building
08034 Barcelona, Catalonia (Spain)
T: +34 93 567 9926
F: +34 93 553 2520
W: http://dana.i2cat.net

**Comment by vmaffione** [comment]
ACK, tests work for me, it is ok to be merged

**Comment by lbergesio** [comment]
Cool!

I think there is not going to be further specific testing of this one, so I
would say that if it is ok with you go ahead

2016-01-21 17:04 GMT+01:00 Vincenzo Maffione <notifications@github.com>:

> ACK, tests work for me, it is ok to be merged
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/820#issuecomment-173618026>.
>



-- 
Leonardo Bergesio
Distributed Applications and Networks Area - DANA
i2CAT Foundation - www.i2cat.net
C/ Gran Capità 2-4, office 109, Nexus I building
08034 Barcelona, Catalonia (Spain)
T: +34 93 567 9926
F: +34 93 553 2520
W: http://dana.i2cat.net

**Comment by vmaffione** [comment]
Nice, merging this

**Pull request merged**
