### PR TITLE
Pristine 1.4 rmtwf clean

### PR DESCRIPTION
**Pull request by lbergesio**
This PR depends on #781 of pristine-1.3.

The set of policies for the RMT's PS has been changed according to experience in
Recent experience developing diffrent RMT's PSs (cherish/urgency, red, jain) has
shown that the current set of policies for the RMT were wrong. Most of them were
never used and many times accommodating to them made the code more complicated.

The new api contemplates the following policies:
```
	struct pdu *(*rmt_dequeue_policy)(struct rmt_ps *,
					  struct rmt_n1_port *);
	int (*rmt_enqueue_policy)(struct rmt_ps *,
				  struct rmt_n1_port *,
				  struct pdu *);
	int (*rmt_q_create_policy)(struct rmt_ps *,
				   struct rmt_n1_port *);
	int (*rmt_q_destroy_policy)(struct rmt_ps *,
				    struct rmt_n1_port *);
	int (*rmt_needs_sched_policy(struct rmt_ps *,
				     struct rmt_n1_port *);
```
The rmt_enqueue_policy policy return code is the following:
- ```RMT_PS_ENQ_SCHED```:	PDU was enqueued properly, RMT mechanism must schedule
			(currently set a tasklet).
- ```RMT_PS_ENQ_DSEND```:	No need to schedule, ownership of PDU by policy is
			rejected, it must be directly sent by the RMT mechanism.
- ```RMT_PS_ENQ_DROP```: 	N-1 Port's queue's full or for some other reason PDU has
			been dropped.
- ```RMT_PS_ENQ_ERR```:	Something went wrong.

Locking in the RMT was also fixed and improved following a reference counting approach to safely delete elements (n1_ports, etc).

Maintainers:
@lbergesio; ==> @edugrasa, @miqueltarzan for my part
F: linux/net/rina/efcp.c
F: plugins/cong_avoidance/rmt-ps-cas.c
F: plugins/dummy/rmt-ps-dummy.c
F: plugins/red/rmt-ps-red.c

@miqueltarzan 
F: linux/net/rina/ipcps/normal-ipcp.c
F: linux/net/rina/rmt-ps-default.c
F: linux/net/rina/rmt-ps-default.h
F: linux/net/rina/rmt-ps.h
F: linux/net/rina/rmt.c
F: linux/net/rina/rmt.h

@vmaffione 
F: linux/net/rina/pci.c

### CODE REVIEW

**Comment by vmaffione** [comment]
This PR has something wrong, I see replicated commits (rebase-related, maybe). It can't be merged in its current state. @lbergesio , can you just put your modifications in one commit containing the diff with pristine-1.4 (that right now should be aligned with pristine-1.3)? It's the easiest solution, imho.

**Comment by lbergesio** [comment]
What is wrong with it? which commits are replicated? This is based on pristine 1.3 which is not merged in pristine-1.4, reason why you see that many commits. The ones introduced by me are the last 6 commits (from c194a2b to 1e480c8). The previous 6 (from 3e4d7fb to f5b66bf) are from PR #781 which is a prerequisite. The rest are already in pristine 1.3 but not 1.4

**Comment by lbergesio** [comment]
I have seen that you merged pristine-1.3 in pristine-1.4. This PR was fine before doing that and now it is not automatically updated to include just the diff. If I create a new PR between the same branches it gets ok (just the 12 last commits), but it does not allow me to create it but redirects me to this one because they are the same...
I guess you can try to merge it  and check it goes well or I can just delete this one, copy the description and create it again tomorrow...

**Comment by vmaffione** [comment]
Yes, I don't know what happened exactly, but as soon as those "replicated
commits" go away it's ok.

2015-11-04 19:45 GMT+01:00 Leonardo Bergesio <notifications@github.com>:

> I have seen that you merged pristine-1.3 in pristine-1.4. This PR was fine
> before doing that and now it is not automatically updated to include just
> the diff. If I create a new PR between the same branches it gets ok (just
> the 12 last commits), but it does not allow me to create it but redirects
> me to this one because they are the same...
> I guess you can try to merge it and check it goes well or I can just
> delete this one, copy the description and create it again tomorrow...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/782#issuecomment-153826105>.
>



-- 
Vincenzo Maffione

**Comment by lbergesio** [comment]
It is supposed to be ok now. Still #781  must go first (and hope that when merging it this one will not break again...)

**Comment by vmaffione** [comment]
Yes, it looks ok now, thanks.

**Comment by edugrasa** [comment]
ACK, tried with 3 systems, normal over normal over shim.eth and encryption enabled. Didn't notice an enhancement or degradation of performance. Nice refactor, now the RMT-ps API and the RMT workflow are much simpler.

**Comment by miqueltarzan** [comment]
ACK

**Comment by edugrasa** [comment]
@vmaffione could you take a look when you have time? Thanks :)

**Comment by vmaffione** [comment]
It seems ok to me (for sure for my maintainer part). Not tested, but have you checked that (RMT) plugins compile and install successfully?

**Comment by edugrasa** [comment]
Yes, I tried compilation and installation, Leo also verified the functionality. Merging then!

**Comment by vmaffione** [comment]
Sure!

2015-11-10 17:21 GMT+01:00 Eduard Grasa <notifications@github.com>:

> Yes, I tried compilation and installation, Leo also verified the
> functionality. Merging then!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/782#issuecomment-155471279>.
>



-- 
Vincenzo Maffione

**Pull request merged**
