### PR TITLE
Fixed two bugs in kernel space (non-present SDU protection config handling and destruction of normal over normal)

### PR DESCRIPTION
**Pull request by edugrasa**
* Fixed null pointer access when destroying a normal IPCP over a normal IPCP with a flow allocated
* Fix handling of not-present SDU protection configuration in kernel space (Fixes issue #675)

Maintainers: @lbergesio @miqueltarzan

### CODE REVIEW

**Comment by lbergesio** [comment]
@edugrasa: we still miss some infrastructure in the kernel for sdu protection, right? The way it is currently done in the n1_port_create and n1_port_write in rmt.c does not allow to plug different code without changing the "core". Anyway this is a parallel discussion...

this fix is ok, ACK

**Comment by edugrasa** [comment]
Yes, sdk support is being addressed by Ondrej

**Comment by lbergesio** [comment]
ack, fixed as discussed

**Comment by miqueltarzan** [comment]
ACK

**Comment by dstaesse** [comment]
Since it goes into the kernel, should this commit now be according to the kernel coding guidelines?
In that case, things need to be corrected.

**Pull request merged**
