### PR TITLE
Pristine 1.5 segfault

### PR DESCRIPTION
**Pull request by edugrasa**
@jmuchemb could you test this one? I think that it should fix all segfaults related to deleting the enrollment state machines ...

### CODE REVIEW

**Comment by jmuchemb** [comment]
These changes are simpler and written in a more reliable way than my last attempt. However, in #1020 I mentioned a probable race condition between abortion and release, and I don't see how this PR would fix it.

First, I added the following assertion at the beginning of `IEnrollmentStateMachine::abortEnrollment`:
```c++
       assert(!lock_.trylock());
```
I got:
```
#0  0x00007f6f23e7c198 in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f6f23e7d61a in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007f6f23e750d7 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007f6f23e75182 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x0000000000430779 in rinad::IEnrollmentStateMachine::abortEnrollment (this=0x6b1900, remotePeerNamingInfo=..., portId=2, reason="Timeout waiting for connect response", sendReleaseMessage=sendReleaseMessage@entry=true)
    at /root/stack/rinad/src/ipcp/enrollment-task.cc:527
#5  0x00000000004307d1 in rinad::EnrollmentFailedTimerTask::run (this=<optimized out>) at /root/stack/rinad/src/ipcp/enrollment-task.cc:608
#6  0x00007f6f2551908a in rina::doWorkTask (arg=0x6a9310) at /root/stack/librina/src/timer.cc:61
#7  0x00007f6f24a8d444 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#8  0x00007f6f23f3020d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```
Then I did:
```diff
@@ -599,4 +604,5 @@ EnrollmentFailedTimerTask::EnrollmentFailedTimerTask(IEnrollmentStateMachine * s
 void EnrollmentFailedTimerTask::run() {
        try {
+               rina::ScopedLock g(state_machine_->lock_);
                state_machine_->abortEnrollment(state_machine_->remote_peer_.name_,
                                                state_machine_->con.port_id,
```
And the following crash confirms my doubt:
```
1172(2016-10-07 09:53:22.2638)#ipcp (INFO): IEnrollmentStateMachine::abortEnrollment(re6st.2.16:1:Management:, 2, Could not assign a valid address, 1, tid=1188)
1172(2016-10-07 09:53:22.2638)#librina.syscalls (DBG): Invoking SYS_readManagementSDU (329)
1172(2016-10-07 09:53:22.3868)#librina.nl-manager (DBG): NL msg RX. Fam: 22; Opcode: 22_QUERY_RIB_REQ; Sport: 1; Dport: 1172; Seqnum: 92; Request; SIPCP: 0; DIPCP: 2
1172(2016-10-07 09:53:22.3869)#librina.core (DBG): Added event of type 19_QUERY_RIB and sequence number 92 to events queue
1172(2016-10-07 09:53:22.3869)#ipcp[2].core (DBG): Got event of type 19_QUERY_RIB and sequence number 92
1172(2016-10-07 09:53:22.3873)#librina.nl-manager (DBG): NL msg TX. Fam: 22; Opcode: 23_QUERY_RIB_RESP; Sport: 1172; Dport: 1; Seqnum: 92; Response; SIPCP: 2; DIPCP: 0
1172(2016-10-07 09:53:22.3874)#librina.nl-manager (DBG): NL msg TX. Fam: 22; Opcode: 25_DUMP_FT_REQ; Sport: 1172; Dport: 0; Seqnum: 1475833708; Request; SIPCP: 2; DIPCP: 2
1172(2016-10-07 09:53:22.3877)#librina.nl-manager (DBG): NL msg RX. Fam: 22; Opcode: 26_DUMP_FT_RESP; Sport: 0; Dport: 1172; Seqnum: 1475833708; Response; SIPCP: 2; DIPCP: 0
1172(2016-10-07 09:53:22.3878)#librina.core (DBG): Added event of type 34_DUMP_FT_RESPONSE and sequence number 1475833708 to events queue
1172(2016-10-07 09:53:22.3879)#ipcp[2].core (DBG): Got event of type 34_DUMP_FT_RESPONSE and sequence number 1475833708
1172(2016-10-07 09:53:22.3879)#ipcp[2].core (DBG): Contents of the PDU Forwarding Table:
Address: 1; QoS-id: 0; Port-ids: 1, ;
Address: 3; QoS-id: 0; Port-ids: 0, ;

1172(2016-10-07 09:53:22.7607)#ipcp[2].enrollment-task (ERR): An error happened during enrollment of remote IPC Process re6st.2.16-1-Management- because of Could not assign a valid address (portId=2, tid=3760)
1172(2016-10-07 09:53:22.7609)#ipcp[2].enrollment-task (DBG): Removing enrollment state machine associated to 2
1172(2016-10-07 09:53:22.7610)#librina.timer (DBG): Waiting for the timer -603963536 to join
1172(2016-10-07 09:53:23.2610)#librina.timer (DBG): Timer with ID -603963536 ended
1172(2016-10-07 09:53:23.2613)#librina.syscalls (DBG): Invoking SYS_writeManagementSDU (330)
1172(2016-10-07 09:53:23.2753)#librina.syscalls (DBG): Syscall write mgt SDU failed: 14
1172(2016-10-07 09:53:23.2756)#ipcp[2].rib-daemon (DBG): Received CDAP message from N-1 port 2
Opcode: 2_M_RELEASE
Flags: 0
Invoke id: 3

1172(2016-10-07 09:53:23.2758)#ipcp (DBG): M_RELEASE cdapMessage from portId 2
1172(2016-10-07 09:53:23.2758)#ipcp[2].enrollment-task (DBG): Removing enrollment state machine associated to 2
1172(2016-10-07 09:53:23.2760)#ipcp[2] (CRIT): Got signal 11
1172(2016-10-07 09:53:23.2760)#rinad-debug (DBG): Cannot dump a backtrace
1172(2016-10-07 09:53:23.2763)#ipcp[2].enrollment-task (ERR): Problems closing application connection: Problems writing SDU to flow
1172(2016-10-07 09:53:23.2765)#ipcp[2].enrollment-task (ERR): Problems deallocating N-1 flow: <A0><8A>i
1172(2016-10-07 09:53:23.2804)#librina.nl-manager (DBG): NL msg RX. Fam: 22; Opcode: 50_APP_FLOW_DEALLOC_NOT; Sport: 1; Dport: 1172; Seqnum: 0; Notification; SIPCP: 0; DIPCP: 2
1172(2016-10-07 09:53:23.2805)#librina.core (DBG): Added event of type 6_FLOW_DEALLOCATED and sequence number 0 to events queue
1172(2016-10-07 09:53:23.2807)#ipcp[2].core (DBG): Got event of type 6_FLOW_DEALLOCATED and sequence number 0
1172(2016-10-07 09:53:23.2808)#librina.irm (ERR): Problems communicating with the IPC Manager: Unknown flow
1172(2016-10-07 09:53:23.2809)#librina.irm (ERR): Problems deleting object from the RIB:
1172(2016-10-07 09:53:23.2810)#internal-events (INFO): Event <E0><E0>i has just happened. Notifying event listeners.
1172(2016-10-07 09:53:23.2892)#librina.nl-manager (DBG): Netlink Manager destructor called
1172(2016-10-07 09:53:23.2900)#librina.concurrency (CRIT): Cannot destroy condition variable
1172(2016-10-07 09:53:23.2901)#librina.concurrency (CRIT): Cannot destroy mutex
3765(2016-10-07 09:53:27.4426)#librina.logs (DBG): New log level: DBG
```
I don't have a traceback but this looks exactly the same as in my first comment of #1020.

(from now on, I'll remove the sigsegv handler in my tests: systemd-coredump is more useful for me)

**Comment by edugrasa** [comment]
Hi @jmuchemb, it was a really stupid error from my side (forgot to check for a null pointer). Sorry for that! This PR should fix the case you have reported.. could you give it a try? Thanks!

**Comment by jmuchemb** [comment]
At the beginning of `logFunc`, I added:
```c++
	assert(level > CRIT);
```
otherwise, the crashes that follow such logs give useless traceback.

Not sure if it's related but I got:
```
#3  0x00007f1da9cfb182 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f1dab39d1d1 in logFunc (level=level@entry=CRIT, fmt=fmt@entry=0x7f1dab4271e8 "librina.concurrency (CRIT): %s. Error is: %d\n") at /root/stack/librina/src/logs.cc:116
#5  0x00007f1dab39e633 in rina::Thread::join (this=<optimized out>, status=status@entry=0x7ffd77ebb838) at /root/stack/librina/src/concurrency.cc:322
#6  0x00007f1dab39f2e4 in rina::Timer::cancel (this=this@entry=0x7f1da00048d0) at /root/stack/librina/src/timer.cc:208
#7  0x00007f1dab39fb7e in rina::Timer::~Timer (this=0x7f1da00048d0, __in_chrg=<optimized out>) at /root/stack/librina/src/timer.cc:175
#8  0x00007f1dab3ccb96 in rina::cdap::ConnectionStateMachine::~ConnectionStateMachine (this=0x7f1da0004880, __in_chrg=<optimized out>) at /root/stack/librina/src/cdap_v2.cc:947
#9  0x00007f1dab3ccbe9 in rina::cdap::ConnectionStateMachine::~ConnectionStateMachine (this=0x7f1da0004880, __in_chrg=<optimized out>) at /root/stack/librina/src/cdap_v2.cc:953
#10 0x00007f1dab3d23e3 in rina::cdap::CDAPSession::~CDAPSession (this=0x7f1da0004660, __in_chrg=<optimized out>) at /root/stack/librina/src/cdap_v2.cc:1549
#11 0x00007f1dab3d273e in rina::cdap::CDAPSessionManager::removeCDAPSession (this=0x6a27f0, port_id=2) at /root/stack/librina/src/cdap_v2.cc:2203
#12 0x00007f1dab3b7a04 in rina::SimpleInternalEventManager::deliverEvent (this=0x69a7f0, event=0x6a9180) at /root/stack/librina/src/internal-events.cc:115
#13 0x00007f1dab3fc0bf in rina::IPCResourceManager::cleanFlowAndNotify (this=0x6a1e90, portId=2) at /root/stack/librina/src/irm.cc:312
#14 0x00007f1dab3fc246 in rina::IPCResourceManager::flowDeallocatedRemotely (this=<optimized out>, event=...) at /root/stack/librina/src/irm.cc:297
#15 0x000000000046656b in rinad::IPCProcessImpl::event_loop (this=0x69ed20) at /root/stack/rinad/src/ipcp/ipc-process.cc:657
#16 0x0000000000424e74 in Main::wrapped_main (this=this@entry=0x7ffd77ebbf70, argc=argc@entry=7, argv=argv@entry=0x7ffd77ebc218) at /root/stack/rinad/src/ipcp/main.cc:74
#17 0x000000000042368d in main (argc=7, argv=0x7ffd77ebc218) at /root/stack/rinad/src/ipcp/main.cc:151
```
and also:
```
#3  0x00007f3cb109c182 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007f3cb273e1d1 in logFunc (level=level@entry=CRIT, fmt=fmt@entry=0x7f3cb27c81e8 "librina.concurrency (CRIT): %s. Error is: %d\n") at /root/stack/librina/src/logs.cc:116
#5  0x00007f3cb273f633 in rina::Thread::join (this=<optimized out>, status=status@entry=0x7f3cafb63228) at /root/stack/librina/src/concurrency.cc:322
#6  0x00007f3cb27402e4 in rina::Timer::cancel (this=this@entry=0x7f3ca8003b80) at /root/stack/librina/src/timer.cc:208
#7  0x00007f3cb2740b7e in rina::Timer::~Timer (this=0x7f3ca8003b80, __in_chrg=<optimized out>) at /root/stack/librina/src/timer.cc:175
#8  0x00007f3cb276db96 in rina::cdap::ConnectionStateMachine::~ConnectionStateMachine (this=0x7f3ca8003b30, __in_chrg=<optimized out>) at /root/stack/librina/src/cdap_v2.cc:947
#9  0x00007f3cb276dbe9 in rina::cdap::ConnectionStateMachine::~ConnectionStateMachine (this=0x7f3ca8003b30, __in_chrg=<optimized out>) at /root/stack/librina/src/cdap_v2.cc:953
#10 0x00007f3cb27733e3 in rina::cdap::CDAPSession::~CDAPSession (this=0x7f3ca8003910, __in_chrg=<optimized out>) at /root/stack/librina/src/cdap_v2.cc:1549
#11 0x00007f3cb277373e in rina::cdap::CDAPSessionManager::removeCDAPSession (this=0x6a27f0, port_id=1) at /root/stack/librina/src/cdap_v2.cc:2203
#12 0x00007f3cb276fe28 in rina::cdap::ConnectionStateMachine::releaseReceived (this=0x7f3ca8003b30, message=...) at /root/stack/librina/src/cdap_v2.cc:1144
#13 0x00007f3cb276fef9 in rina::cdap::ConnectionStateMachine::releaseSentOrReceived (this=<optimized out>, cdap_message=..., sent=sent@entry=false) at /root/stack/librina/src/cdap_v2.cc:1023
#14 0x00007f3cb277487e in rina::cdap::CDAPSession::messageSentOrReceived (this=0x7f3ca8003910, cdap_message=..., sent=sent@entry=false) at /root/stack/librina/src/cdap_v2.cc:1739
#15 0x00007f3cb2774bc7 in rina::cdap::CDAPSession::messageReceived (this=<optimized out>, cdap_message=...) at /root/stack/librina/src/cdap_v2.cc:1711
#16 0x00007f3cb2774c5c in rina::cdap::CDAPSessionManager::messageReceived (this=0x6a27f0, encoded_cdap_message=..., result=..., port_id=1) at /root/stack/librina/src/cdap_v2.cc:2263
#17 0x000000000042c044 in rinad::IPCPCDAPIOHandler::process_message (this=0x6a2940, message=..., handle=1, cdap_dest=<optimized out>) at /root/stack/rinad/src/ipcp/rib-daemon.cc:212
#18 0x000000000042ac00 in rinad::doManagementSDUReaderWork (arg=0x6a3a00) at /root/stack/rinad/src/ipcp/rib-daemon.cc:72
#19 0x00007f3cb1cb4444 in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
#20 0x00007f3cb115720d in clone () from /lib/x86_64-linux-gnu/libc.so.6
```

In the first case, the log was:
```
1037(2016-10-07 14:33:37.4606)#ipcp (INFO): IEnrollmentStateMachine::abortEnrollment(re6st.2.16:1:Management:, 2, Could not assign a valid address, 1, tid=1068)
1037(2016-10-07 14:33:37.4608)#librina.syscalls (DBG): Invoking SYS_readManagementSDU (329)
1037(2016-10-07 14:33:37.9558)#ipcp[2].enrollment-task (ERR): An error happened during enrollment of remote IPC Process re6st.2.16-1-Management- because of Could not assign a valid address (portId=2, tid=2155)
1037(2016-10-07 14:33:37.9558)#ipcp[2].enrollment-task (DBG): Removing enrollment state machine associated to 2
1037(2016-10-07 14:33:37.9559)#librina.timer (DBG): Waiting for the timer -1610599984 to join
1037(2016-10-07 14:33:38.4559)#librina.timer (DBG): Timer with ID -1610599984 ended
1037(2016-10-07 14:33:38.4565)#librina.syscalls (DBG): Invoking SYS_writeManagementSDU (330)
1037(2016-10-07 14:33:38.4638)#ipcp[2].rib-daemon (DBG): Sent CDAP message of size 51 through port-id 2:
Opcode: 2_M_RELEASE
Flags: 0
Invoke id: 1

1037(2016-10-07 14:33:38.4641)#cdap (DBG): Waiting timeout 10000 to receive a release response
1037(2016-10-07 14:33:38.4696)#librina.ipc-api (DBG): Application re6st.0.16 requested to deallocate flow with port-id 2
1037(2016-10-07 14:33:38.4739)#librina.timer (DBG): Waiting for the timer -1610599680 to join
1037(2016-10-07 14:33:38.4744)#librina.nl-manager (DBG): NL msg RX. Fam: 22; Opcode: 50_APP_FLOW_DEALLOC_NOT; Sport: 1; Dport: 1037; Seqnum: 0; Notification; SIPCP: 0; DIPCP: 2
1037(2016-10-07 14:33:38.4753)#librina.core (DBG): Added event of type 6_FLOW_DEALLOCATED and sequence number 0 to events queue
1037(2016-10-07 14:33:38.4755)#ipcp[2].core (DBG): Got event of type 6_FLOW_DEALLOCATED and sequence number 0
1037(2016-10-07 14:33:38.4759)#librina.nl-manager (DBG): NL msg TX. Fam: 22; Opcode: 48_APP_DEALLOC_FLOW_REQ; Sport: 1037; Dport: 1; Seqnum: 1475850713; Request; SIPCP: 0; DIPCP: 0
1037(2016-10-07 14:33:38.4761)#rib (DBG): Removing object over RIB(0x6a2b40) instance id: '39' fqn: '/ipcManagement/irm/underflows/portId=2'
1037(2016-10-07 14:33:38.4792)#rib (DBG): Object '/ipcManagement/irm/underflows/portId=2' of class 'UnderlayingFlow' succesfully removed (id:'39')
1037(2016-10-07 14:33:38.4793)#internal-events (INFO): Event N_MINUS_1_FLOW_DEALLOCATED has just happened. Notifying event listeners.
1037(2016-10-07 14:33:38.4793)#librina.timer (DBG): Waiting for the timer -1610599680 to join
```

**Comment by edugrasa** [comment]
Hi Julien,

Not completely sure I understood what you just explained :) By the log you post at the bottom, it seems that segfaults are gone and you have another type of issue? Or segfaults are still there?

**Comment by jmuchemb** [comment]
It becomes more difficult to reproduce segfaults but I only get those just after an enrollment failure, so it makes sense to first suppose that there's a relation and that this PR does not fix the issue completely.

I don't know the code well enough and the patches don't really answer the questions I raised. I let you judge. If you think this PR goes in the right direction then let's merge with jmuchemb/irati-stack@7e2afda4d8ea6e6e6a31048aba8c2c38ac0518b8 (I always tested with it). (Otherwise, well, 	discreet bugs are hard to identify/fix.)

**Comment by edugrasa** [comment]
Hi @jmuchemb,

Checked the code, there was one class in cdapv2 that was totally missing locking.. No wonder there are race conditions. Could you try again?

**Comment by jmuchemb** [comment]
I have something that looks like a dead lock. On all my 3 VMs, the IPCP is stuck and the 'query-rib' console command fails.

1st VM (but similar strace/traceback of the main thread for the other 2):
```
strace: Process 1010 attached
futex(0x6a2800, FUTEX_WAIT_PRIVATE, 2, NULL
```
```
#0  0x00007f40fc31ce7c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007f40fc316af5 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007f40fcd9e83f in rina::Lockable::lock (this=<optimized out>) at /root/stack/librina/src/concurrency.cc:423
#3  0x00007f40fcdd1e0a in rina::cdap::CDAPSessionManager::get_cdap_session (this=0x6a27f0, port_id=2) at /root/stack/librina/src/cdap_v2.cc:2192
#4  0x00007f40fcdd3e03 in rina::cdap::CDAPSessionManager::getOpenConnectionRequestMessage (this=0x6a27f0, msg=..., con=...) at /root/stack/librina/src/cdap_v2.cc:2346
#5  0x00007f40fcdd361d in rina::cdap::CDAPProvider::remote_open_connection (this=0x6a2940, ver=..., src=..., dest=..., auth=..., port=2) at /root/stack/librina/src/cdap_v2.cc:2939
#6  0x00007f40fcdda43d in rina::rib::RIBDaemonProxy::remote_open_connection (this=<optimized out>, ver=..., src=..., dest=..., auth=..., port_id=2) at /root/stack/librina/src/rib_v2.cc:3484
#7  0x00007f40f8fa50c5 in rinad::EnrolleeStateMachine::initiateEnrollment (this=0x6b0a10, enrollmentRequest=..., portId=2) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:363
#8  0x00007f40f8fa5840 in rinad::EnrollmentTaskPs::initiate_enrollment (this=0x6ac780, event=..., request=...) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:1695
#9  0x000000000043349a in rinad::EnrollmentTask::nMinusOneFlowAllocated (this=0x6a1660, flowEvent=0x6b03a0) at /root/stack/rinad/src/ipcp/enrollment-task.cc:1135
#10 0x00007f40fcdb8964 in rina::SimpleInternalEventManager::deliverEvent (this=0x69a7f0, event=0x6b03a0) at /root/stack/librina/src/internal-events.cc:115
#11 0x00007f40fcdfdd95 in rina::IPCResourceManager::allocateRequestResult (this=0x6a1e90, event=...) at /root/stack/librina/src/irm.cc:185
#12 0x0000000000466625 in rinad::IPCProcessImpl::event_loop (this=0x69ed20) at /root/stack/rinad/src/ipcp/ipc-process.cc:634
#13 0x0000000000424e74 in Main::wrapped_main (this=this@entry=0x7ffc61ba79f0, argc=argc@entry=7, argv=argv@entry=0x7ffc61ba7c98) at /root/stack/rinad/src/ipcp/main.cc:74
#14 0x000000000042368d in main (argc=7, argv=0x7ffc61ba7c98) at /root/stack/rinad/src/ipcp/main.cc:151
```

**Comment by edugrasa** [comment]
Again, my fault for going too fast.. Should be fixed now!

2016-10-10 12:13 GMT+02:00 Julien Muchembled <notifications@github.com>:

**Comment by edugrasa** [comment]
I introduced it .. (facepalm), could you check again?

**Comment by jmuchemb** [comment]
```
#0  0x00007ff6261c1e7c in __lll_lock_wait () from /lib/x86_64-linux-gnu/libpthread.so.0
#1  0x00007ff6261bbaf5 in pthread_mutex_lock () from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007ff626c438bf in rina::Lockable::lock (this=<optimized out>) at /root/stack/librina/src/concurrency.cc:423
#3  0x00007ff626c7a06e in rina::cdap::CDAPSessionManager::createCDAPSession (this=0x6a27f0, port_id=2) at /root/stack/librina/src/cdap_v2.cc:2150
#4  0x00007ff626c78f0c in rina::cdap::CDAPSessionManager::getOpenConnectionRequestMessage (this=0x6a27f0, msg=..., con=...) at /root/stack/librina/src/cdap_v2.cc:2353
#5  0x00007ff626c786dd in rina::cdap::CDAPProvider::remote_open_connection (this=0x6a2940, ver=..., src=..., dest=..., auth=..., port=2) at /root/stack/librina/src/cdap_v2.cc:2944
#6  0x00007ff626c7f4fd in rina::rib::RIBDaemonProxy::remote_open_connection (this=<optimized out>, ver=..., src=..., dest=..., auth=..., port_id=2) at /root/stack/librina/src/rib_v2.cc:3484
#7  0x00007ff622e4a0c5 in rinad::EnrolleeStateMachine::initiateEnrollment (this=0x6b0a10, enrollmentRequest=..., portId=2) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:363
#8  0x00007ff622e4a840 in rinad::EnrollmentTaskPs::initiate_enrollment (this=0x6ac780, event=..., request=...) at /root/stack/rinad/src/ipcp/plugins/default/enrollment-task-ps.cc:1695
#9  0x000000000043349a in rinad::EnrollmentTask::nMinusOneFlowAllocated (this=0x6a1660, flowEvent=0x6b03a0) at /root/stack/rinad/src/ipcp/enrollment-task.cc:1135
#10 0x00007ff626c5d9e4 in rina::SimpleInternalEventManager::deliverEvent (this=0x69a7f0, event=0x6b03a0) at /root/stack/librina/src/internal-events.cc:115
#11 0x00007ff626ca2e55 in rina::IPCResourceManager::allocateRequestResult (this=0x6a1e90, event=...) at /root/stack/librina/src/irm.cc:185
#12 0x0000000000466625 in rinad::IPCProcessImpl::event_loop (this=0x69ed20) at /root/stack/rinad/src/ipcp/ipc-process.cc:634
#13 0x0000000000424e74 in Main::wrapped_main (this=this@entry=0x7fff374c5bf0, argc=argc@entry=7, argv=argv@entry=0x7fff374c5e98) at /root/stack/rinad/src/ipcp/main.cc:74
#14 0x000000000042368d in main (argc=7, argv=0x7fff374c5e98) at /root/stack/rinad/src/ipcp/main.cc:151
```
I am retrying with a similar patch as your last one (internal_createCDAPSession).

**Comment by edugrasa** [comment]
Fixed, sorry again. This time I've actually tested it (that the deadlocks are not there for enrollment)

**Comment by jmuchemb** [comment]
Please add jmuchemb/irati-stack@d8ae8d6774a67169f222a0ac7d4c8c665c576c15.
Testing this is time consuming and I can't reproduce any of the previous segfaults, so I stop here for this issue.

**Pull request merged**
