### PR TITLE
Arcfire modules

### LINKED ISSUE #1095: Package all kernel code as modules
* Get rid of Linux source code in the IRATI repo (create kernel folder containing the kernel code in net/rina)
* Adapdt Makefile from rlite to build kernel code
* Get rid of netlink workarounds
* Compile against 4.9 kernel (latest long term support) - adapt RINA code if required
* Update build scripts and documentation
* Remember to update buildroot

### PR DESCRIPTION
**Pull request by edugrasa**
Moved all RINA kernel code to modules (fixes #1095). Requires Linux kernel 4.9+

* Removed linux folder, moved all RINA kernel code to /kernel
* Changed build system and RINA kernel code to build everything as kernel modules
* Updated code to Linux kernel 4.9
* Fixed compilation warnings
* Got rid of NL workarounds (all apps running over IRATI require the CAP_NET_ADMIN capability to work now, otherwise NL messages between user-space processes cannot be sent)
* Updated build documentation
* Updated kernel plugins makefile

@vmaffione could you give it a try? Thanks!

### CODE REVIEW

**Comment by vmaffione** [comment]
````
$ make
make -C /lib/modules/`uname -r`/build REGRESSION_TESTS=n HAVE_VMPI=n TCP_UDP_BUFFER_SIZE=1500 M=/home/vmaffione/git/nxw/irati/kernel modules
make[1]: Entering directory '/usr/lib/modules/4.10.13-1-ARCH/build'
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/core.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/utils.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rstr.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rmem.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rmap.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rwq.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rbmp.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rqueue.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rfifo.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/ringq.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rref.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rtimer.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/robjects.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rds/rds.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/iodev.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rnl-utils.o
  CC [M]  /home/vmaffione/git/nxw/irati/kernel/rnl.o
/home/vmaffione/git/nxw/irati/kernel/rnl.c:55:20: error: ‘GENL_ID_GENERATE’ undeclared here (not in a function)
         .id      = GENL_ID_GENERATE,
                    ^~~~~~~~~~~~~~~~
/home/vmaffione/git/nxw/irati/kernel/rnl.c: In function ‘rnl_init’:
/home/vmaffione/git/nxw/irati/kernel/rnl.c:671:15: error: implicit declaration of function ‘genl_register_family_with_ops’ [-Werror=implicit-function-declaration]
         ret = genl_register_family_with_ops(&rnl_nl_family, nl_ops);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:295: /home/vmaffione/git/nxw/irati/kernel/rnl.o] Error 1
make[1]: *** [Makefile:1490: _module_/home/vmaffione/git/nxw/irati/kernel] Error 2
make[1]: Leaving directory '/usr/lib/modules/4.10.13-1-ARCH/build'
make: *** [Makefile:12: all] Error 2

````

**Comment by edugrasa** [comment]
It is tested with Linux 4.9, not 4.10. I've just checked and in 4.10 the Netlink APIs have changed, so we'll have to update the IRATI code when we move to Linux 4.9.

**Comment by vmaffione** [comment]
we can discuss this further at the meeting, but what is the intended workflow for the user to install irati?
Maybe you want the user to install a 4.9 version on her machine, and then install irati?
This means that if the user has to install 4.9 in addition to its existing kernel (which is likely to be different).

**Comment by vmaffione** [comment]
Ok, using 4.9 it works.
There is still an issue, that is you need superuser privileges to use the RINA API.

**Pull request merged**
