### PR TITLE
rinad: updated DIF allocator to handle same app registered in many DIFs

### PR DESCRIPTION
**Pull request by edugrasa**
And automatically pick the right one. Tested, seems to work ok with no regressions.

@vmaffione could you take a look? Thanks!

### CODE REVIEW

**Comment by vmaffione** [comment]
It looks ok, I will also test it.

**Comment by vmaffione** [comment]
My tests are OK, can you confirm it works in the VPN scenario we discussed?

**Comment by vmaffione** [comment]
Anyway, we can merge in the meanwhile

**Comment by edugrasa** [comment]
Yeap, tomorrow I will test it!

2016-11-16 22:40 GMT+01:00 Vincenzo Maffione <notifications@github.com>:

**Pull request merged**
