### PR TITLE
First refactor of RMT PS for pristine-1.3

### PR DESCRIPTION
**Pull request by lbergesio**
First, a refactor of the RMT PS to line up with the work done in the SDK and heading to #744 and #745 for pristine-1.4.

-rmt-ps-common.[ch] has been removed and sent back to rmt-ps-default.c
-RMT's default PS data model has been simplified removing generalities targeted for a "common" use.

Second, several bug fixes discovered while debugging the code in this PR:
#778  
#776 
#777 

Maintainers:
I would propose @vmaffione to take a look at this too, considering that the work on the rmt-ps-default is to be completed (it is already done) for 1.4.

@lbergesio
linux/net/rina/efcp.c
linux/net/rina/kipcm.c

@miqueltarzan 	
linux/net/rina/ipcps/normal-ipcp.c
linux/net/rina/rmt-ps-default.c
linux/net/rina/rmt.c

### CODE REVIEW

**Comment by miqueltarzan** [comment]
ACK

**Comment by edugrasa** [comment]
ACK, tested with normal over normal, 3 nodes, using encryption. @vmaffione could you take a look tomorrow morning? (just to the code, don't need to test again) In case you don't have time I'll merge it tomorrow anyway to move forward.

**Comment by vmaffione** [comment]
Yeah, I'll take a look in the next days.

**Comment by edugrasa** [comment]
Hi @vmaffione, in the next days means today? :) It's a short one, and I would like to merge it today if possible.

**Comment by vmaffione** [comment]
ok, I can take a look at it today

2015-11-05 9:52 GMT+01:00 Eduard Grasa <notifications@github.com>:

> Hi @vmaffione <https://github.com/vmaffione>, in the next days means
> today? :) It's a short one, and I would like to merge it today if possible.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/781#issuecomment-153991900>.
>



-- 
Vincenzo Maffione

**Comment by vmaffione** [comment]
ACK for tests, but could you explain better why are you introducing a new waitqueue to wait for pending operations to complete before destroying the EFCP connection? I mean, it seems correct, but since it was not there before, can you elaborate on what bugs/problems you were seing before and you don't see anymore?

**Comment by lbergesio** [comment]
Please  check #778 and https://github.com/lbergesio/stack/commit/f5b66bf626802e842fc4ba28e73ca8f8cd6a4c62

**Comment by vmaffione** [comment]
I see, thanks for the explanation!

**Comment by lbergesio** [comment]
No problem!

**Pull request merged**
