### PR TITLE
Pristine 1.4 fix valgrind closure

### PR DESCRIPTION
**Pull request by bernatgaston**
Fixed 2 errors:
1. A protobuffer closure problem that was introducing memory leaks when closing the ipcm
2. The capture of the SIGINT signal by the IPCP and the closure of the IPCP without segfaults.

Need ack from @vmaffione and @edugrasa

### CODE REVIEW

**Comment by edugrasa** [comment]
ACK, confirmed working. Nice fix!
@vmaffione could you check this one when you have time? Thanks :)

**Comment by vmaffione** [comment]
yes, testing it

**Comment by vmaffione** [comment]
tried to sigint a running IPCP, it seems to behave nicely.
Is that what I should expect?
````
334(1452690330)#librina.syscalls (DBG): Invoking SYS_readManagementSDU (329)
334(1452690349)#ipcp[4] (CRIT): Got signal 2
334(1452690349)#ipcp[4] (DBG): Exited event loop
334(1452690349)#librina.application (INFO): Pluggable component 'security-manager'/'default' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'security-manager'/'PSOC_authentication-none' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'security-manager'/'PSOC_authentication-password' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'security-manager'/'PSOC_authentication-ssh2' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'flow-allocator'/'default' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'flow-allocator'/'RoundRobin' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'namespace-manager'/'default' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'resource-allocator'/'default' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'enrollment-task'/'default' [default] unpublished
334(1452690349)#librina.application (INFO): Pluggable component 'routing'/'link-state' [default] unpublished
334(1452690349)#librina.application (INFO): Plugin default unloaded successfully
334(1452690349)#librina.application (ERR): Pluggable component security-manager/PSOC_authentication-none not found
334(1452690349)#librina.application (ERR): Pluggable component security-manager/PSOC_authentication-password not found
334(1452690349)#librina.application (ERR): Pluggable component security-manager/PSOC_authentication-ssh2 not found
334(1452690349)#librina.nl-manager (DBG): Netlink Manager destructor called
330(1452690349)#librina.nl-manager (DBG): NL msg RX. Fam: 25; Opcode: 27_SOCK_CLOSED_NOT; Sport: 0; Dport: 1; Seqnum: 0; Notification; SIPCP: 0; DIPCP: 0 
330(1452690349)#librina.core (DBG): NL socket at port 334 is closed
330(1452690349)#librina.core (DBG): Added event of type 22_OS_PROCESS_FINALIZED and sequence number 0 to events queue
330(1452690349)#librina.core (DBG): Waiting for message 1
330(1452690349)#ipcm (DBG): Got event of type 22_OS_PROCESS_FINALIZED and sequence number 0
330(1452690349)#ipcm.app (INFO)[os_process_finalized_handler]: Application n.1.IPCP:1::terminated

330(1452690349)#librina.nl-manager (DBG): NL msg RX. Fam: 25; Opcode: 16_ICPM_DEALLOC_FLOW_RESP; Sport: 0; Dport: 1; Seqnum: 12; Response; SIPCP: 1; DIPCP: 0 
330(1452690349)#librina.nl-manager (DBG): NL msg TX. Fam: 25; Opcode: 15_IPCM_DEALLOC_FLOW_REQ; Sport: 1; Dport: 0; Seqnum: 12; Request; SIPCP: 0; DIPCP: 1
330(1452690349)#librina.core (DBG): Added event of type 25_IPCM_DEALLOCATE_FLOW_RESPONSE and sequence number 12 to events queue
330(1452690349)#librina.core (DBG): Waiting for message 1
330(1452690349)#ipcm.flow-alloc (INFO)[deallocate_flow]: Application ::: asks IPC process eth.1.IPCP:1:: to deallocate flow [port-id = 1]

330(1452690349)#librina.nl-manager (DBG): NL msg RX. Fam: 25; Opcode: 21_IPCM_UNREG_APP_RESP; Sport: 0; Dport: 1; Seqnum: 13; Response; SIPCP: 1; DIPCP: 0 
330(1452690349)#librina.nl-manager (DBG): NL msg TX. Fam: 25; Opcode: 20_IPCM_UNREG_APP_REQ; Sport: 1; Dport: 0; Seqnum: 13; Request; SIPCP: 0; DIPCP: 1
330(1452690349)#librina.core (DBG): Added event of type 24_IPCM_UNREGISTER_APP_RESPONSE and sequence number 13 to events queue
330(1452690349)#librina.core (DBG): Waiting for message 1
330(1452690349)#ipcm (INFO)[unregister_app_from_ipcp]: Requested unregistration of application n.1.IPCP:1:: from IPC process eth.1.IPCP:1::

330(1452690349)#ipcm.mad (DBG): IPCP 'n.1.IPCP'(4) has CRASHED!
330(1452690349)#rib (ERR): Unable to remove object 'ld'; the object has children
330(1452690349)#ipcm.mad.ribd_v1 (ERR): Unable to delete an IPCP object '/computingSystemID=1/processingSystemID=1/kernelApplicationProcess/osApplicationProcess/ipcProcesses/ipcProcessID=4'
330(1452690349)#ipcm.mad (DBG): IPCP 'n.1.IPCP'(4) is about to be destroyed...
330(1452690349)#rib (ERR): Unable to remove object 'ld'; the object has children
330(1452690349)#ipcm.mad.ribd_v1 (ERR): Unable to delete an IPCP object '/computingSystemID=1/processingSystemID=1/kernelApplicationProcess/osApplicationProcess/ipcProcesses/ipcProcessID=4'
330(1452690349)#librina.syscalls (DBG): Invoking SYS_destroyIPCProcess (324)
330(1452690350)#ipcm (INFO)[destroy_ipcp]: IPC process destroyed [id = 4]

330(1452690350)#ipcm (DBG): Got event of type 25_IPCM_DEALLOCATE_FLOW_RESPONSE and sequence number 12
330(1452690350)#ipcm.flow-alloc (INFO)[ipcm_deallocate_flow_response_event_handler]: Deallocated flow identified by port-id 1 from IPC process eth.1.IPCP:1:: [success = 1]

330(1452690350)#ipcm (DBG): Got event of type 24_IPCM_UNREGISTER_APP_RESPONSE and sequence number 13
````

**Comment by bernatgaston** [comment]
Yes, as I said in the PR description, the IPCP closes without segfaults. I still need to work more on the closure to be sure that it don't contain memory leaks or bad logs (like the ones you showed). But I'll do this in a new PR.

**Comment by vmaffione** [comment]
nice, ACK

**Pull request merged**
