### PR TITLE
Agent merge

### PR DESCRIPTION
**Pull request by bernatgaston**
This is the work that has been done in the MAD including the RIB of the MAD and some updates in the librina API (v2) of CDAP and RIB. It has been checked and launched, tests checked also.
Need ack from
@edugrasa 
@msune 
@dstaesse

### CODE REVIEW

**Comment by edugrasa** [comment]
ACK (just checked the files I maintain, not tested it)

**Comment by vmaffione** [comment]
Usual test work on my side.
However, this PR does not follow the rules that we estabilished in the Oslo meeting:

- This PR is huge --> difficult to test and analyze
- Description is very generic and incomplete
- Some commits should be squashed (e.g. "tc to be squashed")

At least, would it be possible to have an extensive description of what is contained here (+4000 Klocs)?

**Comment by bernatgaston** [comment]
Yes you are right, this PR contains work previous to Oslo meeting, moreover we will change the way to work since marc is leaving the development and we won't be using the bisdn repository anymore. From now on we will be working directly against pristine-x and not against the bisdn repository, producing much smaller PR. 

On the other side, I have talked with @msune and we will be squazing some of the commits.

On the description point. It basically contains the v2 of the RIB and CDAP that should allow the delegation and that has cleaned the APIS hiding the internal plumbing that was public on the previous API. However, the v1 is still there and being used, so right now both versions can cohabitate. It also contains the MAD implementation which is a new feature to the stack.

We will be squashing some commits and then comming back to you for the PR. In the meantime, we will wait for @dstaesse ack.

**Comment by vmaffione** [comment]
Ok but, MAD implementation is not new to the stack. It's been year for many months. So what does this PR adds to the pristine-1.3 MAD implementation?

**Comment by bernatgaston** [comment]
Ok here a more detailes update of what has been added:
1. CDAP v2 minor updates to simplify initialization and finalization and to clean the API
2. RIB v2 major updates to allow delegation of object functionality.
3. Basic MAD RIB object functionalities added
4. Basic MAD RIB object encoders/decoders added
5. MAD allowed to use multiple RIB versions
6. Manager adapted to use RIB and CDAP v2
7. Manager functionality updated to control 3 nodes (experiment D5.1)
8. RIB test added

**Comment by vmaffione** [comment]
Thanks Bernat!

I'll ask for more information (if you can provide them)

2015-09-15 18:00 GMT+02:00 Bernat <notifications@github.com>:

> Ok here a more detailes update of what has been added:
> 1. CDAP v2 minor updates to simplify initialization and finalization and
> to clean the API
> 2. RIB v2 major updates to allow delegation of object functionality.
>
Can you explain how is delegation supposed to work, e.g. how the RIB
decides what objects are going to be delegated, and
 what is the "delegation" channel --> netlink is assumed?

> 3. Basic MAD RIB object functionalities added
> 4. Basic MAD RIB object encoders/decoders added
>
Ok, regarding the objects that have been added: I guess they are part of
the MOM, but the MOM is huge. Do we have a list of the object (the branches
of the MOM tree) that have been covered so far?

> 5. MAD allowed to use multiple RIB versions
> 6. Manager adapted to use RIB and CDAP v2
> 7. Manager functionality updated to control 3 nodes (experiment D5.1)
>
Ok, I guess we are talking about the "fake" manager, used for functional
testing of the MA.

8. RIB test added
>

Are the tests available with "make check" in  rinad?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/736#issuecomment-140442543>.
>



-- 
Vincenzo Maffione

**Comment by msune** [comment]
@vmaffione 

The PR just adds the RIB (and only RIB) delegation framework. The exact *use* that the MAD has to do with this delegation framwork, is another issue. Delegation in the MAD is not implemented.

For the rest of the architectural discussions about how delegation has to work, please use the mailing list. This discussion should be strictly about the contents of this PR.

**Comment by vmaffione** [comment]
@msune 
Right, in fact I didn't want to discuss, just to know in some more detail how this delegation framework is supposed to work.

**Comment by dstaesse** [comment]
ACK for changes to rina-tools

**Pull request merged**
