### PR TITLE
kernel: pff-ps: add pff_port_state_change() op

### PR DESCRIPTION
**Pull request by vmaffione**
The pff_port_state_change() operation has been added to the policy set in order to receive notifications about flow going up or down.

### CODE REVIEW

**Comment by vmaffione** [comment]
Maintainers: @miqueltarzan @sandervrijders

**Comment by miqueltarzan** [comment]
ACK

**Comment by sandervrijders** [comment]
Seems to fail:

```
[  629.211076] rina-shim-eth-vlan(DBG): Ignoring event 9 on device eth23.110
[  629.211892] rina-shim-eth-vlan(INFO): Device eth23.110 goes down
[  629.211896] rina-normal-ipc(INFO): N-1 flow with pid 1 went down
[  629.211898] rina-normal-ipc(ERR): rmt_port_state_change() failed
```

**Comment by sandervrijders** [comment]
As discussed with @vmaffione in chat: This seems due to memory corruption somewhere. Accessing 'ps' at different moments in time:

```
[  126.007228] rina-pff(DBG): nhop: Pointer value is ffff8803286bce40
[  140.163830] rina-pff(DBG): port state change: Pointer value is ffff880326c75b08
```

Looking for a solution and proposing a patch in a different PR once it is found.

**Comment by sandervrijders** [comment]
@miqueltarzan @lbergesio @edugrasa 

Been investigating with @vmaffione the whole day and it seems we are facing an unknown memory corruption problem somewhere in the stack (kernel space). This PR sometimes works and sometimes it doesn't, although it doesn't do any memory operations itself. When I print out the pointers, it reveals they are sometimes corrupted over a certain timeframe. So, please help squash this bug ASAP, since it is very blocking. Creating an issue.

**Comment by msune** [comment]
Plwhenever reporting a bug (or possible bug) please attach the steps to reproduce it, so that it can be confirmed and fixed.

**Comment by sandervrijders** [comment]
Right, so the steps to reproduce:

1) enroll between two nodes
2) bring an interface down on either one of the nodes

(Maybe step 1) is not even needed, didn't try it)

**Comment by edugrasa** [comment]
Question for @sandervrijders . The memory corruption you see is always in the ps pointer?
Or you've seen it in other places as well? (trying to find the bounds of the problem)

**Comment by sandervrijders** [comment]
I've also seen it in the RMT pointer that is kept in normal-ipcp.c

**Comment by vmaffione** [comment]
Confirmed, sometimes seeing it in the ps pointer, sometimes I see the RMT pointer zeroed (which cannot be).

**Comment by vmaffione** [comment]
Bug should be fixed now (it is on my side), please confirm.

**Comment by edugrasa** [comment]
ACK, problem fixed (I also didn't notice the mistake when reviewing the PR.. we need holidays :))

**Pull request merged**
