### PR TITLE
kernel: implementation of partial read

### LINKED ISSUE #1075: Implement partial read
At the KFA, allow reads that are smaller than the bytes available in the SDU

### PR DESCRIPTION
**Pull request by edugrasa**
Implementation of partial read. I've checked that there are no regressions for complete reads, but @vmaffione could you check that the partial read indeed works? (since you have already dropbear, etc. setup?) Thanks!

Fix #1075

### CODE REVIEW

**Comment by vmaffione** [comment]
On server:

````
a login: [  143.999850] rina-ringq(INFO): RINGQ ffff880006052f00:ffff880006052f00:ffff880005327520:ffff880005327520 created successfully
[  144.001285] rina-ringq(INFO): RINGQ ffff8800009cb200:ffff8800009cb200:ffff880005327720:ffff880005327720 created successfully
[  144.004071] ------------[ cut here ]------------
[  144.004898] kernel BUG at net/core/skbuff.c:1178!
[  144.005839] invalid opcode: 0000 [#1] PREEMPT SMP 
[  144.006669] Modules linked in: rina_default_plugin shim_eth_vlan rinarp arp826 8021q mrp virtio_net ppdev parport_pc parport bochs_drm ttm button intel_agp intel_gtt virtio_pci acpi_cpufreq processor virtio_ring drm_kms_helper virtio joydev mousedev i2c_piix4 drm syscopyarea sysfillrect sysimgblt psmouse evdev mac_hid pcspkr sch_fq_codel ip_tables x_tables ext4 crc16 mbcache jbd2 sr_mod sd_mod cdrom ata_generic pata_acpi serio_raw atkbd libps2 ata_piix libata floppy scsi_mod i8042 serio
[  144.006669] CPU: 0 PID: 1067 Comm: dropbear Not tainted 4.1.38-irati #35
[  144.006669] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.10.1-0-g8891697-prebuilt.qemu-project.org 04/01/2014
[  144.006669] task: ffff88000604a840 ti: ffff8800052a4000 task.ti: ffff8800052a4000
[  144.006669] RIP: 0010:[<ffffffff8148942e>]  [<ffffffff8148942e>] pskb_expand_head+0x24e/0x250
[  144.006669] RSP: 0018:ffff8800052a76f8  EFLAGS: 00010202
[  144.006669] RAX: 0000000000000002 RBX: ffff880005f33200 RCX: 0000000000000020
[  144.006669] RDX: 00000000000002c0 RSI: 0000000000000000 RDI: ffff880005f33200
[  144.006669] RBP: ffff8800052a7738 R08: ffff8800059126ac R09: 0000000000000001
[  144.006669] R10: ffffffff814c0250 R11: 0000000000000293 R12: 000000000000112c
[  144.006669] R13: 00000004001c0029 R14: 0000000000000081 R15: ffff880005f33200
[  144.006669] FS:  00007f2449cba740(0000) GS:ffff880007800000(0000) knlGS:0000000000000000
[  144.006669] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  144.006669] CR2: 00000000024371c0 CR3: 00000000051b6000 CR4: 00000000000006f0
[  144.006669] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  144.006669] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  144.006669] Stack:
[  144.006669]  0000000000000000 ffff8800059126ac ffff8800052a7738 ffff880005f33200
[  144.006669]  000000000000112c 00000004001c0029 0000000000000081 ffff88000650d000
[  144.006669]  ffff8800052a7788 ffffffff8149dcf5 0000000000000000 0000000000000000
[  144.006669] Call Trace:
[  144.006669]  [<ffffffff8149dcf5>] validate_xmit_skb.isra.34.part.35+0x2a5/0x2e0
[  144.006669]  [<ffffffff8149e7b3>] validate_xmit_skb_list+0x43/0x70
[  144.006669]  [<ffffffff814c134b>] sch_direct_xmit+0x17b/0x230
[  144.006669]  [<ffffffff814c150c>] __qdisc_run+0x10c/0x1b0
[  144.006669]  [<ffffffff8149e4a6>] __dev_queue_xmit+0x326/0x5c0
[  144.006669]  [<ffffffff8149e753>] dev_queue_xmit_sk+0x13/0x20
[  144.006669]  [<ffffffffa02d5967>] vlan_dev_hard_start_xmit+0xa7/0x130 [8021q]
[  144.006669]  [<ffffffff8149dfa5>] dev_hard_start_xmit+0x275/0x450
[  144.006669]  [<ffffffff8149da6e>] ? validate_xmit_skb.isra.34.part.35+0x1e/0x2e0
[  144.006669]  [<ffffffff8149e6ce>] __dev_queue_xmit+0x54e/0x5c0
[  144.006669]  [<ffffffff8149e753>] dev_queue_xmit_sk+0x13/0x20
[  144.006669]  [<ffffffffa02eacd2>] eth_vlan_sdu_write+0x172/0x300 [shim_eth_vlan]
[  144.006669]  [<ffffffff815afa87>] n1_port_write_sdu+0x47/0xf0
[  144.006669]  [<ffffffff815b0786>] rmt_send_port_id+0x1e6/0x2b0
[  144.006669]  [<ffffffff815b08fd>] rmt_send+0xad/0x170
[  144.006669]  [<ffffffff815a6d18>] dt_pdu_send+0x68/0x140
[  144.006669]  [<ffffffff815b9632>] default_transmission_control+0x62/0xb0
[  144.006669]  [<ffffffff815ac3da>] dtp_write+0x1ca/0x510
[  144.006669]  [<ffffffff815adc9b>] efcp_container_write+0xbb/0x200
[  144.006669]  [<ffffffff815bda32>] normal_sdu_write+0xb2/0xe0
[  144.006669]  [<ffffffff815b2661>] kfa_flow_sdu_write+0x251/0x4c0
[  144.006669]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  144.006669]  [<ffffffff815b6f90>] kipcm_sdu_write+0x60/0xe0
[  144.006669]  [<ffffffff815993fc>] iodev_write+0x7c/0xd0
[  144.006669]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  144.006669]  [<ffffffff811e6f95>] do_loop_readv_writev+0x75/0xa0
[  144.006669]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  144.006669]  [<ffffffff811e7a25>] do_readv_writev+0x235/0x260
[  144.006669]  [<ffffffff811e7ad9>] vfs_writev+0x39/0x50
[  144.006669]  [<ffffffff811e88c9>] SyS_writev+0x59/0x100
[  144.006669]  [<ffffffff810ebde1>] ? SyS_clock_gettime+0x81/0xd0
[  144.006669]  [<ffffffff815d3cae>] system_call_fastpath+0x12/0x71
[  144.006669] Code: 75 1a 41 8b 87 cc 00 00 00 49 03 87 d0 00 00 00 e9 c2 fe ff ff b8 f4 ff ff ff eb 96 4c 89 ef e8 99 18 d4 ff b8 f4 ff ff ff eb 87 <0f> 0b 0f 1f 44 00 00 55 48 89 e5 41 57 41 56 41 55 41 54 41 89 
[  144.006669] RIP  [<ffffffff8148942e>] pskb_expand_head+0x24e/0x250
[  144.006669]  RSP <ffff8800052a76f8>
[  144.111255] ---[ end trace 21439094b2a24dab ]---
[  144.112765] Kernel panic - not syncing: Fatal exception in interrupt
[  144.114500] Kernel Offset: disabled
[  144.114567] drm_kms_helper: panic occurred, switching back to text console
[  144.114567] ---[ end Kernel panic - not syncing: Fatal exception in interrupt
````

On client:
````
c login: [  143.973002] rina-ringq(INFO): RINGQ ffff88000019e3c0:ffff88000019e3c0:ffff8800051e51a0:ffff8800051e51a0 created successfully
[  143.975683] rina-ringq(INFO): RINGQ ffff88000019ee40:ffff88000019ee40:ffff8800051e5ee0:ffff8800051e5ee0 created successfully
[  143.986140] ------------[ cut here ]------------
[  143.987155] kernel BUG at net/core/skbuff.c:1178!
[  143.988159] invalid opcode: 0000 [#1] PREEMPT SMP 
[  143.988992] Modules linked in: rina_default_plugin shim_eth_vlan rinarp arp826 8021q mrp joydev bochs_drm virtio_net ppdev mousedev ttm drm_kms_helper drm syscopyarea sysfillrect evdev intel_agp intel_gtt i2c_piix4 sysimgblt virtio_pci psmouse pcspkr virtio_ring virtio mac_hid parport_pc parport acpi_cpufreq processor button sch_fq_codel ip_tables x_tables ext4 crc16 mbcache jbd2 sr_mod sd_mod cdrom ata_generic pata_acpi serio_raw atkbd libps2 ata_piix libata scsi_mod floppy i8042 serio
[  143.989145] CPU: 1 PID: 1056 Comm: dbclient Not tainted 4.1.38-irati #35
[  143.989145] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.10.1-0-g8891697-prebuilt.qemu-project.org 04/01/2014
[  143.989145] task: ffff880005c98000 ti: ffff8800051c4000 task.ti: ffff8800051c4000
[  143.989145] RIP: 0010:[<ffffffff8148942e>]  [<ffffffff8148942e>] pskb_expand_head+0x24e/0x250
[  143.989145] RSP: 0018:ffff8800051c76f8  EFLAGS: 00010202
[  143.989145] RAX: 0000000000000002 RBX: ffff8800058c8300 RCX: 0000000000000020
[  143.989145] RDX: 00000000000002c0 RSI: 0000000000000000 RDI: ffff8800058c8300
[  143.989145] RBP: ffff8800051c7738 R08: ffff88000597d6ac R09: 0000000000000001
[  143.989145] R10: ffffffff814c0250 R11: 0000000000000293 R12: 0000000000001190
[  143.989145] R13: 00000004001c0029 R14: 0000000000000081 R15: ffff8800058c8300
[  143.989145] FS:  00007f9561195740(0000) GS:ffff880007900000(0000) knlGS:0000000000000000
[  143.989145] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  143.989145] CR2: 00000000006c6438 CR3: 0000000000165000 CR4: 00000000000006e0
[  143.989145] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  143.989145] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  143.989145] Stack:
[  143.989145]  0000000000000000 ffff88000597d6ac ffff8800051c7738 ffff8800058c8300
[  143.989145]  0000000000001190 00000004001c0029 0000000000000081 ffff8800050f5000
[  143.989145]  ffff8800051c7788 ffffffff8149dcf5 ffffffff812dedf8 ffff8800051c7778
[  143.989145] Call Trace:
[  143.989145]  [<ffffffff8149dcf5>] validate_xmit_skb.isra.34.part.35+0x2a5/0x2e0
[  143.989145]  [<ffffffff812dedf8>] ? delay_tsc+0x38/0xb0
[  143.989145]  [<ffffffff8118e1a0>] ? zone_statistics+0x80/0xa0
[  143.989145]  [<ffffffff8149e7b3>] validate_xmit_skb_list+0x43/0x70
[  143.989145]  [<ffffffff814c134b>] sch_direct_xmit+0x17b/0x230
[  143.989145]  [<ffffffff814c150c>] __qdisc_run+0x10c/0x1b0
[  143.989145]  [<ffffffff8149e4a6>] __dev_queue_xmit+0x326/0x5c0
[  143.989145]  [<ffffffff8149e753>] dev_queue_xmit_sk+0x13/0x20
[  143.989145]  [<ffffffffa0202967>] vlan_dev_hard_start_xmit+0xa7/0x130 [8021q]
[  143.989145]  [<ffffffff8149dfa5>] dev_hard_start_xmit+0x275/0x450
[  143.989145]  [<ffffffff8149da6e>] ? validate_xmit_skb.isra.34.part.35+0x1e/0x2e0
[  143.989145]  [<ffffffff8149e6ce>] __dev_queue_xmit+0x54e/0x5c0
[  143.989145]  [<ffffffff8149e753>] dev_queue_xmit_sk+0x13/0x20
[  143.989145]  [<ffffffffa02e9cd2>] eth_vlan_sdu_write+0x172/0x300 [shim_eth_vlan]
[  143.989145]  [<ffffffff815afa87>] n1_port_write_sdu+0x47/0xf0
[  143.989145]  [<ffffffff815b0786>] rmt_send_port_id+0x1e6/0x2b0
[  143.989145]  [<ffffffff815b08fd>] rmt_send+0xad/0x170
[  143.989145]  [<ffffffff815a6d18>] dt_pdu_send+0x68/0x140
[  143.989145]  [<ffffffff815b9632>] default_transmission_control+0x62/0xb0
[  143.989145]  [<ffffffff815ac3da>] dtp_write+0x1ca/0x510
[  143.989145]  [<ffffffff815adc9b>] efcp_container_write+0xbb/0x200
[  143.989145]  [<ffffffff815bda32>] normal_sdu_write+0xb2/0xe0
[  143.989145]  [<ffffffff815b2661>] kfa_flow_sdu_write+0x251/0x4c0
[  143.989145]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  143.989145]  [<ffffffff815b6f90>] kipcm_sdu_write+0x60/0xe0
[  143.989145]  [<ffffffff815993fc>] iodev_write+0x7c/0xd0
[  143.989145]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  143.989145]  [<ffffffff811e6f95>] do_loop_readv_writev+0x75/0xa0
[  143.989145]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  143.989145]  [<ffffffff811e7a25>] do_readv_writev+0x235/0x260
[  143.989145]  [<ffffffff811f8b39>] ? do_filp_open+0x49/0xd0
[  143.989145]  [<ffffffff8147e99d>] ? sockfd_lookup_light+0x6d/0x70
[  143.989145]  [<ffffffff81205b32>] ? __fget+0x72/0xb0
[  143.989145]  [<ffffffff811e7ad9>] vfs_writev+0x39/0x50
[  143.989145]  [<ffffffff811e88c9>] SyS_writev+0x59/0x100
[  143.989145]  [<ffffffff815d3cae>] system_call_fastpath+0x12/0x71
[  143.989145] Code: 75 1a 41 8b 87 cc 00 00 00 49 03 87 d0 00 00 00 e9 c2 fe ff ff b8 f4 ff ff ff eb 96 4c 89 ef e8 99 18 d4 ff b8 f4 ff ff ff eb 87 <0f> 0b 0f 1f 44 00 00 55 48 89 e5 41 57 41 56 41 55 41 54 41 89 
[  143.989145] RIP  [<ffffffff8148942e>] pskb_expand_head+0x24e/0x250
[  143.989145]  RSP <ffff8800051c76f8>
[  144.080278] ---[ end trace c1fe3f0f330778c1 ]---
[  144.082450] Kernel panic - not syncing: Fatal exception in interrupt
[  144.083601] Kernel Offset: disabled
[  144.083601] drm_kms_helper: panic occurred, switching back to text console
[  144.083601] ---[ end Kernel panic - not syncing: Fatal exception in interrupt
````

Crash happens right after accept.

**Comment by edugrasa** [comment]
Hi Vincenzo, updated using skb_pull. Could you try again?

**Comment by vmaffione** [comment]
still crashes on server side

````
[  356.069870] rina-ringq(INFO): RINGQ ffff88000635d600:ffff88000635d600:ffff880005e1a320:ffff880005e1a320 created successfully
[  356.070989] rina-ringq(INFO): RINGQ ffff88000635df40:ffff88000635df40:ffff880005e1a520:ffff880005e1a520 created successfully
[  356.073437] ------------[ cut here ]------------
[  356.073884] kernel BUG at net/core/skbuff.c:1178!
[  356.074318] invalid opcode: 0000 [#1] PREEMPT SMP 
[  356.074798] Modules linked in: rina_default_plugin shim_eth_vlan rinarp arp826 8021q mrp virtio_net ppdev bochs_drm ttm drm_kms_helper joydev mousedev drm syscopyarea psmouse pcspkr evdev virtio_pci sysfillrect mac_hid parport_pc parport virtio_ring sysimgblt intel_agp acpi_cpufreq intel_gtt processor i2c_piix4 button virtio sch_fq_codel ip_tables x_tables ext4 crc16 mbcache jbd2 sr_mod cdrom sd_mod ata_generic pata_acpi serio_raw atkbd libps2 ata_piix libata scsi_mod floppy i8042 serio
[  356.076640] CPU: 0 PID: 2140 Comm: dropbear Not tainted 4.1.38-irati #36
[  356.076640] Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.10.1-0-g8891697-prebuilt.qemu-project.org 04/01/2014
[  356.076640] task: ffff880005d78000 ti: ffff88000584c000 task.ti: ffff88000584c000
[  356.076640] RIP: 0010:[<ffffffff8148942e>]  [<ffffffff8148942e>] pskb_expand_head+0x24e/0x250
[  356.076640] RSP: 0018:ffff88000584f6f8  EFLAGS: 00010202
[  356.076640] RAX: 0000000000000002 RBX: ffff880006440b00 RCX: 0000000000000020
[  356.076640] RDX: 00000000000002c0 RSI: 0000000000000000 RDI: ffff880006440b00
[  356.076640] RBP: ffff88000584f738 R08: ffff880006325aac R09: 0000000000000001
[  356.076640] R10: ffffffff814c0250 R11: 0000000000000293 R12: 000000000000112c
[  356.076640] R13: 00000004001c0029 R14: 0000000000000081 R15: ffff880006440b00
[  356.076640] FS:  00007fd41c119740(0000) GS:ffff880007800000(0000) knlGS:0000000000000000
[  356.076640] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  356.076640] CR2: 0000000000a811c0 CR3: 0000000001e62000 CR4: 00000000000006f0
[  356.076640] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  356.076640] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  356.076640] Stack:
[  356.076640]  0000000000000000 ffff880006325aac ffff88000584f738 ffff880006440b00
[  356.076640]  000000000000112c 00000004001c0029 0000000000000081 ffff880005cc5000
[  356.076640]  ffff88000584f788 ffffffff8149dcf5 ffffffff8118e1a0 0000000000000001
[  356.076640] Call Trace:
[  356.076640]  [<ffffffff8149dcf5>] validate_xmit_skb.isra.34.part.35+0x2a5/0x2e0
[  356.076640]  [<ffffffff8118e1a0>] ? zone_statistics+0x80/0xa0
[  356.076640]  [<ffffffff8149e7b3>] validate_xmit_skb_list+0x43/0x70
[  356.076640]  [<ffffffff814c134b>] sch_direct_xmit+0x17b/0x230
[  356.076640]  [<ffffffff814c150c>] __qdisc_run+0x10c/0x1b0
[  356.076640]  [<ffffffff8118e1a0>] ? zone_statistics+0x80/0xa0
[  356.076640]  [<ffffffff8149e4a6>] __dev_queue_xmit+0x326/0x5c0
[  356.076640]  [<ffffffff8149e753>] dev_queue_xmit_sk+0x13/0x20
[  356.076640]  [<ffffffffa02d2967>] vlan_dev_hard_start_xmit+0xa7/0x130 [8021q]
[  356.076640]  [<ffffffff8149dfa5>] dev_hard_start_xmit+0x275/0x450
[  356.076640]  [<ffffffff8149da6e>] ? validate_xmit_skb.isra.34.part.35+0x1e/0x2e0
[  356.076640]  [<ffffffff8149e6ce>] __dev_queue_xmit+0x54e/0x5c0
[  356.076640]  [<ffffffff8149e753>] dev_queue_xmit_sk+0x13/0x20
[  356.076640]  [<ffffffffa02eccd2>] eth_vlan_sdu_write+0x172/0x300 [shim_eth_vlan]
[  356.076640]  [<ffffffff815afa87>] n1_port_write_sdu+0x47/0xf0
[  356.076640]  [<ffffffff815b0786>] rmt_send_port_id+0x1e6/0x2b0
[  356.076640]  [<ffffffff815b08fd>] rmt_send+0xad/0x170
[  356.076640]  [<ffffffff815a6d18>] dt_pdu_send+0x68/0x140
[  356.076640]  [<ffffffff815b9612>] default_transmission_control+0x62/0xb0
[  356.076640]  [<ffffffff815ac3da>] dtp_write+0x1ca/0x510
[  356.076640]  [<ffffffff815adc9b>] efcp_container_write+0xbb/0x200
[  356.076640]  [<ffffffff815bda12>] normal_sdu_write+0xb2/0xe0
[  356.076640]  [<ffffffff815b2661>] kfa_flow_sdu_write+0x251/0x4c0
[  356.076640]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  356.076640]  [<ffffffff815b6f70>] kipcm_sdu_write+0x60/0xe0
[  356.076640]  [<ffffffff815993fc>] iodev_write+0x7c/0xd0
[  356.076640]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  356.076640]  [<ffffffff811e6f95>] do_loop_readv_writev+0x75/0xa0
[  356.076640]  [<ffffffff81599380>] ? iodev_poll+0xa0/0xa0
[  356.076640]  [<ffffffff811e7a25>] do_readv_writev+0x235/0x260
[  356.076640]  [<ffffffff811e7ad9>] vfs_writev+0x39/0x50
[  356.076640]  [<ffffffff811e88c9>] SyS_writev+0x59/0x100
[  356.076640]  [<ffffffff810ebde1>] ? SyS_clock_gettime+0x81/0xd0
[  356.076640]  [<ffffffff815d3dae>] system_call_fastpath+0x12/0x71
[  356.076640] Code: 75 1a 41 8b 87 cc 00 00 00 49 03 87 d0 00 00 00 e9 c2 fe ff ff b8 f4 ff ff ff eb 96 4c 89 ef e8 99 18 d4 ff b8 f4 ff ff ff eb 87 <0f> 0b 0f 1f 44 00 00 55 48 89 e5 41 57 41 56 41 55 41 54 41 89 
[  356.076640] RIP  [<ffffffff8148942e>] pskb_expand_head+0x24e/0x250
[  356.076640]  RSP <ffff88000584f6f8>
[  356.137176] ---[ end trace 35046b6c79eeaa89 ]---
[  356.137823] Kernel panic - not syncing: Fatal exception in interrupt
[  356.138823] Kernel Offset: disabled
[  356.139487] drm_kms_helper: panic occurred, switching back to text console
[  356.140403] ---[ end Kernel panic - not syncing: Fatal exception in interrupt
````

It does not seem to be related to the receive/read side, but to the write side. The bug is on skb_shared() in pskb_expand_head(), which means that somewhere you are cloning the skbuff (that is incrementing skb->users) and you shouldn't

**Comment by edugrasa** [comment]
@vmaffione I've added a partial-read flag to the rina-echo-time application (just used in server mode for the ping test), to be able to test partial read. The bug that showed up was solved in former pull requests. I've tried partial read with different options (doing partial reads of 1, 2, ... N bytes), everything seems to be working fine! Could you try with the dropbear setup? Thanks!

(the syntax for the partial read argument is rina-echo-time -l --partial read N, where N is the max number of bytes read at each _read_ syscall)

**Comment by vmaffione** [comment]
No crash, but dropbear client/server hang:
Server dmesg:
````
[  277.855429] rina-efcp(ERR): Cannot find the requested instance cep-id: 65535
[  277.856438] rina-rmt(ERR): EFCP container problems
[  277.857113] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  277.857986] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
[  277.859147] rina-efcp(ERR): Cannot find the requested instance cep-id: 65535
[  277.862292] rina-rmt(ERR): EFCP container problems
[  277.863176] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  277.865517] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
````
Client dmesg
````
[  277.852018] rina-efcp(ERR): Flow is being deallocated, dropping SDU
[  277.852958] rina-dtp(ERR): Could not enqueue SDU to EFCP
[  277.853789] rina-efcp(ERR): Flow is being deallocated, dropping SDU
[  277.854696] rina-dtp(ERR): Could not enqueue SDU to EFCP
[  277.855527] rina-efcp(ERR): DTP cannot receive this PDU
[  277.857834] rina-rmt(ERR): EFCP container problems
[  277.859353] rina-normal-ipc(ERR): Could not enqueue SDU into the RMT
[  277.861163] rina-shim-eth-vlan(ERR): Couldn't enqueue SDU to user IPCP
````

**Comment by edugrasa** [comment]
It was related to a race condition in the flow allocation code, fixed now. Merging!

**Pull request merged**
