### PR TITLE
Added AS_IF to check that actually the binaries are found

### LINKED ISSUE #709: librina installation fails because AC_PATH_PROG  of PROTOC is not being checked
Hi,

I am trying to install the sdk and I fell into this error:
```
rm -f CDAP.tmp
touch CDAP.tmp
/bin/false -I. -I/home/bird/irati/librina/src	\
	--cpp_out=.		\
	/home/bird/irati/librina/src/CDAP.proto
Makefile:1695: recipe for target 'CDAP.stamp' failed
```
This is caused because during configuration the check of the PROTOC path is failing:
```
checking for management_sdu_write syscall availability... yes
checking for protoc... /bin/false
checking for LIBPROTOBUF... yes
```
The root problem seems to be that the assigned path is not being checked:
https://github.com/IRATI/stack/blob/master/librina/configure.ac#L240

Other paths that are not being checked are:
https://github.com/IRATI/stack/blob/master/rinad/configure.ac#L28-L31
https://github.com/IRATI/stack/blob/master/rina-tools/configure.ac#L31-L34
https://github.com/IRATI/stack/blob/master/librina/configure.ac#L32-L35

### PR DESCRIPTION
**Pull request by vicalro**
Added AS_IF checks and error messages for configuration of librina, rinad, rina-tools.

fixes #709

### CODE REVIEW

**Comment by sandervrijders** [comment]
@vicalro Please specify the maintainers. (check_maintainers.py script in the root) Giving it a try.

**Comment by sandervrijders** [comment]
ACK

Without git:
```
checking for git... no
configure: error: Your system lacks of git support
```

With git:
```
checking for git... /usr/bin/git
```

**Comment by vicalro** [comment]
Need the ack from the maintainer of build system of librina, rinad & rina-tools: @msune

**Comment by msune** [comment]
ACK

**Pull request merged**
