### PR TITLE
Pristine 1.3 lock fixes

### PR DESCRIPTION
**Pull request by miqueltarzan**
Fixed locks in normal-ipcp.c, the data structures were to be accessed both in process and interrupt context.

### CODE REVIEW

**Comment by edugrasa** [comment]
@miqueltarzan you should add the list of maintainers to the PR description (I always forget it too ;))

**Comment by miqueltarzan** [comment]
Maintainers: @lbergesio

**Comment by miqueltarzan** [comment]
@vmaffione  Please, could you test and ack as well? I'm the maintainer of some of the files I changed, a reviewer for them is needed.

**Comment by vmaffione** [comment]
Tested --> ACK

**Pull request merged**
