### PR TITLE
QTAMux implementation, updates to C/Umux, add FA PS to allow selecting QoS

### PR DESCRIPTION
**Pull request by miqueltarzan**
Addresses #858 

Implememtation of a full fledged QTAMux, updated the C/Umux, and implement a Flow Allocator PS that allows selecting QoS cubes based on the maximum delay requested by the application. This was required for the experiments with QTAMux. Also, minor changes in the rina-echo-time application, modifying the perf mode to give estimates of the mean delay and jitter. The server shows the max delay, so it is easier to link the estimates to the QoS cube it was selected.

Maintainers: @edugrasa who is kindly asked to review everything.

### CODE REVIEW

**Comment by edugrasa** [comment]
Hi Miquel,

A couple of comments:

* Does the qta_mux obsole the cherish_urgency plugin? (if so, we should remove it in this PR)
* Could you fix this compilation warning?

````
/root/openirati/plugins/qta_mux/qta-mux.c: In function 'qta_qset_attr_show':
/root/openirati/plugins/qta_mux/qta-mux.c:123:3: warning: format '%u' expects argument of type 'unsigned int', but argument 3 has type 'ssize_t' [-Wformat=]
   return sprintf(buf, "%u\n", qset->occupation);
`````
Thanks :)

**Comment by miqueltarzan** [comment]
Hi Eduard,

- I'll fix the warning ASAP. 
- Regarding the relationship between QTAMux and cherish-urgency plugin: Indeed, QTAMux supersedes cherish-urgency but the QTAMux, as you correctly guessed, is work in progress. However, handling null values for P/S parameters in the QTAMux, cherish-urgency would be obtained as a particular case, and its plugin could be removed. I'll add that.

**Comment by miqueltarzan** [comment]
Fixed compilation warning, checked functionality of cherish-urgency plugin subsumed in QTAMux, removed cherish-urgency plugin

Please @edugrasa could you test it?

**Comment by edugrasa** [comment]
ACK, merging!

**Pull request merged**
