### PR TITLE
Pristine 1.4 kernel upgrade to 4.1.16

### PR DESCRIPTION
**Pull request by vmaffione**
This series of commit introduces incremental upgrades from Linux 4.1.10 (current) up to 4.1.16.

Need ack from
@edugrasa 
@lbergesio 
@miqueltarzan 
@sandervrijders 
@dstaesse 
anybody is developing/testing on openIRATI

### CODE REVIEW

**Comment by vmaffione** [comment]
Integration tests are ok on my side.

**Comment by edugrasa** [comment]
6 hours without crashing with the new kernel, never got this far with 4.1.10, the issue seems to be fixed :)

**Comment by vmaffione** [comment]
Nice :)
Is it still running? We can wait more, to be "sure", if you like.

**Comment by edugrasa** [comment]
Let's wait until tomorrow morning, see how the night goes :P

**Comment by edugrasa** [comment]
Sorry, I hit the wrong button (facepalm)

**Comment by vmaffione** [comment]
yep, let's see how the night goes!!

**Comment by lbergesio** [comment]
24 hs running. Looks good for me.

2016-01-25 21:24 GMT+01:00 Vincenzo Maffione <notifications@github.com>:

> yep, let's see how the night goes!!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/837#issuecomment-174650894>.
>



-- 
Leonardo Bergesio
Distributed Applications and Networks Area - DANA
i2CAT Foundation - www.i2cat.net
C/ Gran Capità 2-4, office 109, Nexus I building
08034 Barcelona, Catalonia (Spain)
T: +34 93 567 9926
F: +34 93 553 2520
W: http://dana.i2cat.net

**Comment by edugrasa** [comment]
Same for me! Bug is gone, ACK :)

**Comment by vmaffione** [comment]
Ok I'll merge!

**Pull request merged**
