### PR TITLE
rina-tools: iporinad: detect and react to closed sessions

### PR DESCRIPTION
**Pull request by vmaffione**
This patch also includes several changes that refactors iporinad
and the fdfwd lib.

### CODE REVIEW

**Comment by edugrasa** [comment]
Compiler fails due to a couple of things:

* the Makefile in rina-tools/src/rlite needs to specify c++11 when compiling the rina-gw
* when compiliing the iporinad file the compiler says it cannot find the <rina/cdap.hpp> header (including "cdap.hpp" as before works)

After compiling I've setup a simple scenario, killed one of the daemons but the other one does not react (flow is deallocated though). Maybe a problem in IRATI?

**Comment by edugrasa** [comment]
I've investigated more.. the flow is deallocated, then the iporinad daemon tries to read the file descriptor associated to the flow, the io-device calls the KFA, who tries to recover the flow, but it doesn't exist and returns return -EBADF.

So the read syscall returns -EBADF, but I can see that iporinad issues another read syscall right away, which reports another error, and so on.. (until I kill the iporinad process). Maybe I should return another error?

**Comment by vmaffione** [comment]
Sorry for the build issues, I just forgot to redo those changes, and I didn't realize the error because I only tried to compile iporinad on my system (that has also the headers installed).

Regarding the EBADF the way to go is that kernel returns 0 to indicate EOF. This is what rlite does, and it's the common way to indicate EOF.
As a side thing, it's not ok that fdfwd loops over an error, I beed to fix that.

**Comment by edugrasa** [comment]
Ok, I'll fix that so it returns 0.

**Comment by vmaffione** [comment]
Fixed the build issues, now it should build correctly.

**Comment by edugrasa** [comment]
It still tries to read the file descriptor, even returning 0.. I'll check again.

**Comment by edugrasa** [comment]
Ok, now it works, it was a problem with the poll implementation in the iodev, fixed!

**Pull request merged**
