### PR TITLE
1109 travis ci

### PR DESCRIPTION
**Pull request by miguelpdl**
This pull request towards the arcfire branch is specifically to add the Gitlab Runner config to the Stack so it can be built on a Gitlab runner. 

An example of a [passing build can be seen over in the GitLab environment](https://gitlab.com/arcfire/irati/stack/pipelines/12409234)

[pipeline status](https://gitlab.com/arcfire/irati/stack/commits/1109-travis-ci)

@edugrasa would you mind re-reviewing this PR ?

### CODE REVIEW

**Comment by edugrasa** [comment]
Looks good (and you have tested it :)). The only detail is that in theory these two dependencies are not needed any more:

sudo apt-get install libnl-genl-3-dev 
 +  - sudo apt-get install libnl-3-dev 

It should be safe to remove them

**Comment by miguelpdl** [comment]
Yes I've now removed these unneeded dependancies, however there is another item to investigate as per the [issue over in Gitlab](https://gitlab.com/arcfire/irati/stack/issues/3#note_42479292).

The possible issues are in the build process itself:

```
make[3]: Entering directory '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/fare'
install fare.so /home/gitlab-runner/install/lib/rinad/ipcp
install: cannot stat ‘fare.so’: No such file or directory
Makefile:36: recipe for target 'install' failed
make[3]: *** [install] Error 1
```

```
/bin/sh: 2: cd: can't cd to Makefile
```

```
/bin/sh: 2: cd: can't cd to README
```

All in the last screen of the [pipeline](https://gitlab.com/arcfire/irati/stack/-/jobs/35042606).
I think someone more familiar with the stack (Eduard?) should review the build process in order to figure out if it really did complete correctly.

If it did indeed not complete correctly, then we might have a problem with the `make` exit status, can you @edugrasa help say for sure ?

**Comment by edugrasa** [comment]
Just fixed the build of the rdsr-ps plugins.. could you give it another go? (it's already merged in the IRATI arcfire branch)

**Comment by miguelpdl** [comment]
Just checked [a recent build of this branch](https://gitlab.com/arcfire/irati/stack/-/jobs/36001160) with [the latest of arcfire branch (Oct 11th) merged into it](https://gitlab.com/arcfire/irati/stack/commits/1109-travis-ci).

2 errors appear:

1) copy of cddr.manifest to the directory /lib/modules/4.9.51/extra/ fails in `plugins/rdsr-ps/cdrr`

```
make[3]: Entering directory '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr'
make -C /lib/modules/4.9.51/build M=$PWD modules_install
make[4]: Entering directory '/home/irati/linux-stable'
  DEPMOD  4.9.51
make[4]: Leaving directory '/home/irati/linux-stable'
cp cddr.manifest /lib/modules/4.9.51/extra/
cp: cannot stat ‘cddr.manifest’: No such file or directory
Makefile:31: recipe for target 'install' failed
make[3]: *** [install] Error 1
make[3]: Leaving directory '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr'

```

2) There's an error with a cd in to a directory Makefile somewhere near either `plugins/rdsr-ps/fare` or `plugins/rdsr-ps/pffb`.

```
make[3]: Entering directory '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/fare'
install fare.so /home/gitlab-runner/install/lib/rinad/ipcp
install -m 0644 fare.manifest /home/gitlab-runner/install/lib/rinad/ipcp
make[3]: Leaving directory '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/fare'
/bin/sh: 2: cd: can't cd to Makefile
make[3]: Entering directory '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/pffb'
```

So @edugrasa appears this branch is still not ready for a merge just yet.

**Comment by edugrasa** [comment]
You can ignore the second error (it is not a real error, it's just how that makefile works, it lists all the files - directories or not- in the folder and tries to cd into them, if it can't - because they are not folders - it just continues). I'll look into the first error, didn't appear in my machines

**Comment by edugrasa** [comment]
A typo I didn't see, sorry! Could you pull and try again? Thanks!

**Comment by miguelpdl** [comment]
I can confirm that `cdrr` plugin build does work which is great !!!!

I shall also ignore the second error as requested.

However and you are going to think this is death by a 1000 cuts @edugrasa  ... but [there's one more final error to resolve](https://gitlab.com/arcfire/irati/stack/-/jobs/36171794):

> #include "pdu.h" is not found in the build path of cdrr. 

Now obviously the build server is missing a dev library some how, but do you know which one ?

```
make[3]: Entering directory '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr'
make -C /lib/modules/4.9.51/build KBUILD_EXTRA_SYMBOLS=/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/../kernel/Module.symvers M=$PWD
make[4]: Entering directory '/home/irati/linux-stable'
  LD      /home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr/built-in.o
  CC [M]  /home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr/dtcp-ps-cdrr.o
/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr/dtcp-ps-cdrr.c:38:17: fatal error: pdu.h: No such file or directory
 #include "pdu.h"
                 ^
compilation terminated.
scripts/Makefile.build:299: recipe for target '/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr/dtcp-ps-cdrr.o' failed
make[5]: *** [/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr/dtcp-ps-cdrr.o] Error 1
Makefile:1493: recipe for target '_module_/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr' failed
make[4]: *** [_module_/home/gitlab-runner/builds/5dd82e11/0/arcfire/irati/stack/plugins/rdsr-ps/cdrr] Error 2
make[4]: Leaving directory '/home/irati/linux-stable'
Makefile:25: recipe for target 'all' failed
```

**Comment by edugrasa** [comment]
Should be fixed now, can you merge and try again? Compilations works well for me (before it had not tried to compile this module because I had not set the INSTALLDIR variable)

**Comment by miguelpdl** [comment]
@edugrasa I can confirm [that the build of this branch works](https://gitlab.com/arcfire/irati/stack/-/jobs/36578428) with no compilation failures.

I think we are nearly there, but we are down to the final questions. 

1) It appears to me that the there is a problem with the make exit status. As in, the previous compilation failures didn't cause the build to stop or show clearly that there was a failure. So in the future if ever there is a compilation failure, the build system cannot alert us to this issue. Is there someway now to cause the make to exit with a status of failure once a compilation error is caught ?

2) There is a minor warning to note in the whole compilation, but may be there's nothing to do here but note it

```
irati/stack/plugins/red/rmt-ps-red.c: In function ‘red_rmt_ps_set_policy_set_param’:
arcfire/irati/stack/plugins/red/rmt-ps-red.c:341:3: warning: ignoring return value of ‘kstrtoul’, declared with attribute warn_unused_result [-Wunused-result]
   kstrtoul(value, 16, (unsigned long *) &user_address);
   ^
```

**Comment by edugrasa** [comment]
Very true. Just cleaned up the required plugin makefiles to exit on error, and also fixed the warning as well. Could you merge and try? That should be it ;)

**Comment by miguelpdl** [comment]
@edugrasa I've merged in those final changes, and [the build has passed](https://gitlab.com/arcfire/irati/stack/-/jobs/36676075) it's all over to you now to consider this merge request.

**Pull request merged**
