### PR TITLE
Shim-eth-vlan bugfixes

### PR DESCRIPTION
**Pull request by sandervrijders**
These two commits fix two issues we had with the shim-eth-vlan, and were discussed during the developer's meeting.

@vmaffione Could you give it a try to see if they are resolved?

### CODE REVIEW

**Comment by jmuchemb** [comment]
Not working for me.
The modules are loaded at boot (/etc/modules) without error reported, before network is up.
Then, I get the following errors when starting IPCM:
````
[   52.641744] rina-arp826-tables(DBG): Adding GPA/GHA couple to the 0xd1f0 ptype table
[   52.641745] rina-arp826-tables(DBG): No table exists for this device yet, creating it
[   52.641746] rina-arp826-tables(DBG): Creating table for ptype = 0xD1F0, hwlen = 6
[   52.641746] rina-arp826-tables(DBG): Creating tbl instance for ha-len 6
[   52.641758] rina-arp826-tables(DBG): Got memory, fillin' it up
[   52.641758] rina-arp826-tables(DBG): Table instance created successfully
[   52.641759] rina-arp826-tables(DBG): Now adding the new table to the tables map
[   52.641763] rina-arp826-tables(DBG): Table for created successfully (device = ffff88000ceb2000, ptype = 0xD1F0, hwlen = 6)
[   52.641772] rina-arp826-tables(DBG): Creating a new table entry for this ARP-add request
[   52.641773] rina-arp826-tables(DBG): Creating new table entry
[   52.641788] rina-arp826-tables(DBG): Table entry ffff88000d713000 created successfully
[   52.641789] rina-arp826-tables(DBG): Adding the GPA/GHA entry to the 0xd1f004 table
[   52.641790] rina-arp826-tables(ERR): Bogus instance, cannot add entry to table
[   52.642006] rina-arp826-tables(ERR): Cannot add to the 0xd1f0 table, rolling back
[   52.642185] rina-shim-eth-vlan(ERR): Failed to register application in ARP
...
[   52.642823] rina-shim-eth-vlan(ERR): Wrong request, app is not registered
[   52.642998] rina-kipcm(ERR): Failed allocating flow request
````

**Comment by sandervrijders** [comment]
@jmuchemb Found the error. I amended the commit. Could you give it another try? Much obliged!

**Comment by jmuchemb** [comment]
Now it works.

**Comment by sandervrijders** [comment]
Cool. @vmaffione Can you merge this in?

**Pull request merged**
