### PR TITLE
Arcfire qta

### PR DESCRIPTION
**Pull request by edugrasa**
* Enhance QTA mux implementation: ease configuration, implement token-bucket policer, fix C/U mux, enhance documentation
* Fix RMT workflow (so that all PDUs go through the RMT policy)
* Fix deadlock in Flow allocator for local flows

### CODE REVIEW

**Comment by vmaffione** [comment]
Sounds good, but any change to the rina api header must be discussed and done together across the prototypes. This is also valid for common applications. Otherwise we end up with code that is not interoperable.

**Comment by vmaffione** [comment]
In this case no changes to the header, so that's ok. However, to avoid conflicts with the rinaperf upstream it would be better to do the change first in the upstream, and then replay those changes in irati. I can do the changes in the upstream and then align irati.

**Comment by edugrasa** [comment]
Hi Vincenzo, ok, let's do it this way. Can I merge this PR and then we merge your changes on top?

**Comment by vmaffione** [comment]
Yes please go ahead

**Pull request merged**
