### PR TITLE
Transaction-based policy-set selection

### PR DESCRIPTION
**Pull request by vmaffione**
kernel: implement transaction-based policy-set selection
This allows easier management of policy sets for the kernel IPCP components.

Requires #768 

Maintainers:
@lbergesio 
@miqueltarzan (RMT part)
@sandervrijders (PFF)

### CODE REVIEW

**Comment by lbergesio** [comment]
I have pulled the code (directly this branch), have done a make distclean, make bzImage modules and finally make modules_install install. I keep getting the following warnings in the last step:

 ```
DEPMOD  3.15.0
WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_sending_ack
WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_rtt_estimator
WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_receiving_flow_control
WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_lost_control_pdu
WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_sender_ack
WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_rate_reduction
WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_rcvr_ack
WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_sending_ack
WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_rtt_estimator
WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_receiving_flow_control
WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_lost_control_pdu
WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_sender_ack
WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_rate_reduction
WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_rcvr_ack
```
So, the old symbols of dtcp-ps-common. Is this only happening to me?

**Comment by vmaffione** [comment]
HI Leonardo,
  It seems you have not recompiled cas-plugin against the new kernel, so
you keep warning because the cas-plugin.ko you have is compiled against the
old kernels, and those symbols disappeared in the transition.

Can you try recompiling the cas-plugin first?

2015-10-26 19:37 GMT+01:00 Leonardo Bergesio <notifications@github.com>:

> I have pulled the code (directly this branch), have done a make distclean,
> make bzImage modules and finally make modules_install install. I keep
> getting the following warnings in the last step:
>
> DEPMOD  3.15.0
> WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_sending_ack
> WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_rtt_estimator
> WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_receiving_flow_control
> WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_lost_control_pdu
> WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_sender_ack
> WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_rate_reduction
> WARNING: /lib/modules/3.15.0/extra/cas-plugin.ko needs unknown symbol common_rcvr_ack
> WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_sending_ack
> WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_rtt_estimator
> WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_receiving_flow_control
> WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_lost_control_pdu
> WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_sender_ack
> WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_rate_reduction
> WARNING: /lib/modules/3.15.0/extra/red-plugin.ko needs unknown symbol common_rcvr_ack
>
> So, the old symbols of dtcp-ps-common. Is this only happening to me?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IRATI/stack/pull/769#issuecomment-151241973>.
>



-- 
Vincenzo Maffione

**Comment by lbergesio** [comment]
I did not see that. You are right, you need to first compile the plugins. Just make, make install as it is in our Makefiles now will fail because it will not find the modules directory (at least in the first installation).

**Comment by lbergesio** [comment]
Update: You NEED to do ``` make install ``` in red and cas plugins, which translates to 
``` 
$(MAKE) -C $(KDIR) M=$$PWD modules_install
cp red-plugin.manifest /lib/modules/$(KREL)/extra/
 ```
and it will later fail because the destination directory does not exist, in order to be able to install the kernel (and modules).

**Comment by lbergesio** [comment]
Ok, not a real problem, this was happening to me because I was building in a machine running the linux4.1 kernel that was there from previous testing.

**Comment by lbergesio** [comment]
ACK, tested with CAS and RED PSs

**Comment by vmaffione** [comment]
Thanks @lbergesio.
Waiting for acknowledge from @miqueltarzan and @sandervrijders

**Comment by sandervrijders** [comment]
ACK

**Comment by miqueltarzan** [comment]
ACK

**Pull request merged**
