### PR TITLE
Arcfire 1.5 sk buff sdup tcp

### PR DESCRIPTION
**Pull request by lbergesio**
SKBuff integrated replacing old buffer struct. All available shims updated.

This pull request replace https://github.com/IRATI/stack/pull/991 which should be closed.

### CODE REVIEW

**Comment by edugrasa** [comment]
Tried a DIF with the SSH2 authentication policies, the crypto module complains about these errors:

````
[18984.684284] rina-sdup-crypto-ps-default(WARN): DECRYPT original buffer_size 416
[18984.688258] rina-sdup-crypto-ps-default(ERR): DBG Compressed size (363), decompressed size (365)
[18984.703779] rina-sdup-crypto-ps-default(ERR): DBG Compressed size (405), uncompressed size (440)
````

**Comment by vmaffione** [comment]
Regression tests (without authentication policies) are ok, with 1 or 2 levels of normal DIFs --> ACK

**Comment by lbergesio** [comment]
Guys, it should be working now

@edugrasa Can you please check again?
@vmaffione  Could you please run regression tests again?

**Comment by vmaffione** [comment]
Regression tests done --> OK

**Comment by edugrasa** [comment]
ACK, errors and crashes are gone!

**Pull request merged**
