### PR TITLE
kernel: shim-eth-vlan: Allow multiple flows between 2 hosts

### PR DESCRIPTION
**Pull request by sandervrijders**
This will allow multiple flows to be established between 2 hosts. If
there is already a flow between two hosts, the next ethertype will be
selected.

### CODE REVIEW

**Comment by vmaffione** [comment]
We should rebase this, conficts arose.

**Comment by vmaffione** [comment]
I solved the conflicts and tried some regression tests (which are ok on the arcfire branch).
Enrollment fails, and I guess it does so because there is some problem transmitting the packets.
Log of a node:
````
355(1474121074)#cdap (DBG): Waiting timeout 10000 to receive a connection response
355(1474121074)#rib (DBG): Starting add object operation over RIB(0xde8860), of object(0xdf0a20) with fqn: '/rmt/n1flows/port_id=1' (parent '/rmt/n1flows')
355(1474121074)#rib (DBG): Add object operation over RIB(0xde8860), of object(0xdf0a20) with fqn: '/rmt/n1flows/port_id=1', succeeded. Instance id: '33'
355(1474121074)#ipcp[2].routing-ps-link-state (DBG): flow allocation waiting for enrollment
355(1474121084)#ipcp[2].enrollment-task (ERR): An error happened during enrollment of remote IPC Process n1.2.IPCP-1-- because of Timeout waiting for connect response
355(1474121084)#ipcp[2].enrollment-task (DBG): Removing enrollment state machine associated to 1
355(1474121084)#librina.nl-manager (DBG): NL msg TX. Fam: 25; Opcode: 8_ENROLL_TO_DIF_RESP; Sport: 355; Dport: 1; Seqnum: 6; Response; SIPCP: 2; DIPCP: 0
355(1474121084)#librina.timer (DBG): Waiting for the timer 14625936 to join
355(1474121084)#cdap (ERR): M_CONNECT_R message not received within 10000 ms. Reseting the connection
355(1474121084)#librina.timer (DBG): Waiting for the timer 14642672 to join
355(1474121085)#librina.timer (DBG): Timer with ID 14642672 ended
355(1474121085)#librina.timer (DBG): Timer with ID 14625936 ended
355(1474121085)#ipcp[2].enrollment-task (ERR): Problems closing application connection: There are no open CDAP sessions associated to the flow identified by 1 right now
355(1474121085)#librina.ipc-api (DBG): Application n1.1.IPCP requested to deallocate flow with port-id 1
355(1474121085)#librina.nl-manager (DBG): NL msg TX. Fam: 25; Opcode: 48_APP_DEALLOC_FLOW_REQ; Sport: 355; Dport: 1; Seqnum: 1474121063; Request; SIPCP: 0; DIPCP: 0
355(1474121085)#librina.nl-manager (DBG): NL msg RX. Fam: 25; Opcode: 49_APP_DEALLOC_FLOW_RESP; Sport: 1; Dport: 355; Seqnum: 1474121063; Response; SIPCP: 0; DIPCP: 2 
355(1474121085)#librina.core (DBG): Added event of type 4_DEALLOCATE_FLOW_RESPONSE and sequence number 1474121063 to events queue
355(1474121085)#ipcp[2].core (DBG): Got event of type 4_DEALLOCATE_FLOW_RESPONSE and sequence number 1474121063
355(1474121085)#rib (DBG): Removing object over RIB(0xde8860) instance id: '32' fqn: '/ipcManagement/irm/underflows/portId=1'
355(1474121085)#rib (DBG): Object '/ipcManagement/irm/underflows/portId=1' of class 'UnderlayingFlow' succesfully removed (id:'32')
355(1474121085)#internal-events (INFO): Event N_MINUS_1_FLOW_DEALLOCATED has just happened. Notifying event listeners.
355(1474121085)#ipcp[2].enrollment-task (DBG): Removing enrollment state machine associated to 1
355(1474121085)#ipcp[2].enrollment-task (INFO): Could not find enrollment state machine associated to port-id 1
355(1474121085)#rib (DBG): Removing object over RIB(0xde8860) instance id: '33' fqn: '/rmt/n1flows/port_id=1'
355(1474121085)#rib (DBG): Object '/rmt/n1flows/port_id=1' of class 'RMTN1Flow' succesfully removed (id:'33')

````

**Comment by edugrasa** [comment]
@sandervrijders since there are conflicts again and @vmaffione reported that it doesn't work properly yet, what about if we close this pull request and you submit it again when the code is ready?

**Comment by sandervrijders** [comment]
Well, I can just add commits on top of this. No need to close it.

**Comment by edugrasa** [comment]
No problems with that if you plan to work on this now. 

I mean, I don't think it is useful to keep PRs open for months.. If they are not ready, we can just close and reopen when they are :)

**Pull request closed without merging**
